### ISSUE TITLE
Correctly hash 'file-uploads' in 'validator_mime.py'

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/machine-learning#1510]
We need to correctly hash *file-uploads* within the `file_upload_validation` method from `validator_mime.py`.  Specifically, we need to resolve the following trace-error:

```python
jeffrey@ubuntu-14:/var/www$ python app.py
 * Running on http://127.0.0.1:5000/
 * Restarting with reloader
127.0.0.1 - - [01/Mar/2015 09:13:30] "POST /load-data/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/web_interface/views.py", line 36, in load_data
    if session_type == 'data_new': response = loader.load_data_new()
  File "/var/www/brain/load_data.py", line 30, in load_data_new
    session.validate_mime_type()
  File "/var/www/brain/session/session_base_data.py", line 31, in validate_mime_type
    self.response_mime_validation = validator.file_upload_validation()
  File "/var/www/brain/validator/validator_mime.py", line 60, in file_upload_validation
    dataset['file_upload'][:] = dataset_keep
TypeError: unhashable type
```

**Comment by jeff1evesque** [comment]
We will remove the `.read()` method, and rename the invocation of `md5_for_file`.

**Comment by jeff1evesque** [comment]
Since we have [renamed](https://github.com/jeff1evesque/machine-learning/issues/1515#ref-commit-a691198)`md5_for_file`, we need to change the following import:

```python
...
from brain.converter.converter_md5 import md5_for_file
...
```

**Comment by jeff1evesque** [comment]
We need to adjust our `mimetype` validation, since we are not provided a file-object.

**Comment by jeff1evesque** [comment]
Also, if we implement the following `print` within `validator_mime.py`:

```python
...
    unique_hash      = set()
    dataset_keep     = []

    if (dataset.get('file_upload', None)):

      print dataset
...
```

we get the following within our traceback:

```python
$ python app.py
 * Running on http://127.0.0.1:5000/
 * Restarting with reloader
{'file_upload': [{'file': <FileStorage: u'sample-1.xml' ('text/xml')>, 'filename': u'sample-1.xml'}, {'file': <FileStorage: u'sample.xml' ('text/xml')>, 'filename': u'sample.xml'}], 'upload_quantity': 2}
...
```

Thus, the following `for` statement can be removed:

```python
...
          # add 'hashed' value of file reference(s) to a list
          if filehash not in unique_hash:
            unique_hash.add(filehash)
            for idx, file in enumerate(filedata['file']):
              mimetype = filedata['file'].content_type
...
```

**Comment by jeff1evesque** [comment]
We need to properly create `dataset_keep`.
