### ISSUE TITLE
Add 'return' logic in 'load_data.py'

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/machine-learning#1540]
Each `load_xx_xx` method in `load_data.py` will need a corresponding `return` statement.  Specifically, we will need to check if `session.return_error()` returns any errors.  If no errors exists, we will `return` a corresponding value in the method.  Properly returning a value, will resolve the following traceback error:

```python
$ python app.py
 * Running on http://127.0.0.1:5000/
 * Restarting with reloader
 * Detected change in '/var/www/web_interface/views.py', reloading
 * Restarting with reloader
127.0.0.1 - - [02/Mar/2015 14:29:33] "POST /load-data/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
```

**Note:** the above suggested `return` value(s) will be used within [`views.py`](https://github.com/jeff1evesque/machine-learning/blob/master/web_interface/views.py).

**Comment by jeff1evesque** [comment]
Our traceback is now clean:

```bash
$ python app.py
 * Running on http://127.0.0.1:5000/
 * Restarting with reloader
127.0.0.1 - - [02/Mar/2015 16:39:25] "POST /load-data/ HTTP/1.1" 200 -
```
