### ISSUE TITLE
Correctly implement 'response_added' in 'data_saver.py'

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/machine-learning#1542]
We need to properly define, and implement `response_added` within `data_saver.py`.  Specifically, we need to eliminate the following traceback error, when a user attempts to upload two or more distinct file-uploads during a `data_new` session:

```bash
$ python app.py
 * Running on http://127.0.0.1:5000/
 * Restarting with reloader
127.0.0.1 - - [02/Mar/2015 16:47:24] "POST /load-data/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/web_interface/views.py", line 36, in load_data
    if session_type == 'data_new': response = loader.load_data_new()
  File "/var/www/brain/load_data.py", line 42, in load_data_new
    session.save_observation_label('data_new', session_id)
  File "/var/www/brain/session/session_data_new.py", line 45, in save_observation_label
    db_return = db_save.db_data_save()
  File "/var/www/brain/database/data_saver.py", line 90, in db_data_save
    else: return { 'status': True, 'error': None, 'id': response_added['id'] }
UnboundLocalError: local variable 'response_added' referenced before assignment
```

**Comment by jeff1evesque** [comment]
If we have the following `print` implementation within `data_saver.py`:

```python
...
    # insert / update feature label(s)
    elif self.svm_cmd == 'save_label':
      self.sql.sql_connect('db_machine_learning')

      print self.svm_data
...
```

we get a traceback similar to the following:

```bash
$ python app.py
 * Running on http://127.0.0.1:5000/
 * Restarting with reloader
{'id_entity': 10L, 'label': 'dep-variable-1'}
{'id_entity': 10L, 'label': 'dep-variable-3'}
{'id_entity': 10L, 'label': 'dep-variable-4'}
{'id_entity': 10L, 'label': 'dep-variable-4'}
127.0.0.1 - - [02/Mar/2015 17:48:04] "POST /load-data/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/web_interface/views.py", line 36, in load_data
    if session_type == 'data_new': response = loader.load_data_new()
  File "/var/www/brain/load_data.py", line 42, in load_data_new
    session.save_observation_label('data_new', session_id)
  File "/var/www/brain/session/session_data_new.py", line 45, in save_observation_label
    db_return = db_save.db_data_save()
  File "/var/www/brain/database/data_saver.py", line 92, in db_data_save
    else: return { 'status': True, 'error': None, 'id': response_added['id'] }
UnboundLocalError: local variable 'response_added' referenced before assignment
```

**Comment by jeff1evesque** [comment]
If we have the following `print` implementation within `data_saver.py`:

```python
...
    # insert / update feature label(s)
    elif self.svm_cmd == 'save_label':
      self.sql.sql_connect('db_machine_learning')

      # add labels (append case)
      if self.session_type in ['data_append', 'data_new']:

        # check if observation label exists in database
        sql_statement = 'SELECT * FROM tbl_observation_label WHERE dep_variable_label=%s AND id_entity=%$
        args          = (self.svm_data['label'], self.svm_data['id_entity'])
        response      = self.sql.sql_command( sql_statement, 'select', args )

        print response
...
```

and, try to upload both [`sample.xml`](https://github.com/jeff1evesque/machine-learning/blob/master/web_interface/static/data/xml/sample.xml), and [`sample-1.xml`](https://github.com/jeff1evesque/machine-learning/blob/master/web_interface/static/data/xml/sample-1.xml) during `data_new` session, we get a traceback similar to the following:

```bash
$ python app.py
 * Running on http://127.0.0.1:5000/
 * Restarting with reloader
{'status': False, 'result': (), 'error': []}
{'status': False, 'result': (), 'error': []}
{'status': False, 'result': (), 'error': []}
{'status': False, 'result': ((33L, 11L, 'dep-variable-4'),), 'error': []}
127.0.0.1 - - [02/Mar/2015 17:51:21] "POST /load-data/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/web_interface/views.py", line 36, in load_data
    if session_type == 'data_new': response = loader.load_data_new()
  File "/var/www/brain/load_data.py", line 42, in load_data_new
    session.save_observation_label('data_new', session_id)
  File "/var/www/brain/session/session_data_new.py", line 45, in save_observation_label
    db_return = db_save.db_data_save()
  File "/var/www/brain/database/data_saver.py", line 92, in db_data_save
    else: return { 'status': True, 'error': None, 'id': response_added['id'] }
UnboundLocalError: local variable 'response_added' referenced before assignment
```

**Comment by jeff1evesque** [comment]
We will undo our earlier [changes](https://github.com/jeff1evesque/machine-learning/issues/1456#ref-commit-45246c3) of implementing `response_added['id']`.

**Comment by jeff1evesque** [comment]
We are now able to upload any number, and combination of csv, or xml files.
