### ISSUE TITLE
Validate incoming dataset + properties

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/machine-learning#1919]
After #1917 has been created, we will add the corresponding validation within the `jsonschema_model_generate` function from `jsonschema_definition.py`.

**Comment by jeff1evesque** [comment]
This issue follows https://github.com/jeff1evesque/machine-learning/issues/1923#issuecomment-223863059.

**Comment by jeff1evesque** [comment]
It seems our schema's are not being used to validate incoming data. More specifically, incoming objects that doesn't not match the schema are not failing, or raising an exception. For example, the following `self.model_settings`, from a `model_generate` session:

```json
{
    'model_type': u'svm',
    'session_type': u'model_generate',
    'collection': u'collection-2',
    'stream': False,
    'sv_kernel_type': u'linear'
}
```

Is not raising an exception with the following schema requirement:

```json
{
      'type': 'object',
      'properties': {
          'session_id': {
              'type': 'string',
              'minLength': 1
          },
          'sv_model_type': {
              'type': 'string',
              'enum': ['svm', 'svr']
          },
          'session_type': {
              'type': 'string',
              'enum': ['model_generate']
          },
    },
}
```

**Comment by jeff1evesque** [comment]
We'll try to implement [voluptuous](https://pypi.python.org/pypi/voluptuous), as a replacement to the current `jsonschema` implementation:

- https://julien.danjou.info/blog/2015/python-schema-validation-voluptuous

This means, we'll likely need to refactor the corresponding `brain/schema/session.py`.

**Comment by jeff1evesque** [comment]
The following tests, are a demonstration of the `voluptuous` package:

```python
>>> test = [{'key1': [{'inner': 'whoa', 'inner2': '3'}], 'key2': 'val2'}, {'key1': [{'inner': 'hahha'}], 'key2': 'jeff2'}]
>>>
>>>
>>> mySchema = Schema([{Required('key1'): [{Required(All(str, Length(min=1))): All(str, Length(min=1))}], Required('key2'): All(str, Length(min=1))}])
>>>
>>>
>>> mySchema(test)
[{'key2': 'val2', 'key1': [{'inner2': '3', 'inner': 'whoa'}]}, {'key2': 'jeff2', 'key1': [{'inner': 'hahha'}]}]
```

**Comment by jeff1evesque** [comment]
The following also validates:

```python
>>> test = [{'key1': [{'inner': 'whoa', 'inner2': '3'}, {'jeff': 'levesque'}], 'key2': 'val2'}, {'key1': [{'inner': 'hahha'}], 'key2': 'jeff2'}]
>>>
>>>
>>> mySchema = Schema([{Required('key1'): [{Required(All(str, Length(min=1))): All(str, Length(min=1))}], Required('key2'): All(str, Length(min=1))}])
>>>
>>>
>>> mySchema(test)
[{'key2': 'val2', 'key1': [{'inner2': '3', 'inner': 'whoa'}, {'jeff': 'levesque'}]}, {'key2': 'jeff2', 'key1': [{'inner': 'hahha'}]}]
```

**Comment by jeff1evesque** [comment]
cf7efd7: since we've [removed](https://github.com/jeff1evesque/machine-learning/commit/e50215b1e2788d527557a21914b307a24a3e1dbb) the `jsonschema` package, our `dataset.py`, needed to be adjusted. Specifically, any `jsonschema` validation, also needed to be converted to using the [`voluptuous`](https://pypi.python.org/pypi/voluptuous) package.

**Comment by jeff1evesque** [comment]
Upon submitting a `data_new` session, we receive the following traceback:

```bash
[2018-01-15 23:11:19,422] {/usr/local/lib/python2.7/dist-packages/flask/app.py:1560} ERROR - Exception on /load-data [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/interface/views_web.py", line 94, in load_data
    response = loader.load_data_new()
  File "/vagrant/brain/load_data.py", line 78, in load_data_new
    session.check()
  File "/vagrant/brain/session/base.py", line 96, in check
    raise Exception(error)
Exception: ["not a valid value for dictionary value @ data['stream']"]
```

**Comment by jeff1evesque** [comment]
We were able to run all sessions layers, to produce, then save corresponding predictions results:

![results](https://user-images.githubusercontent.com/2907085/35069739-1a8422a6-fba9-11e7-93fe-c83b3490575a.JPG)

Now, we may choose to generalize some of validation parameters using hiera.

**Comment by jeff1evesque** [comment]
We also need to verify our svr prediction processes, and ensure corresponding travis builds succeeds.

**Comment by jeff1evesque** [comment]
660f238: we have temporarily committed an `Exception`, to debug our implementation of the `voluptuous` schema validation. The reason for introducing temporary code, is because our current docker container, pulled from dockerhub, have [not taken](https://github.com/jeff1evesque/machine-learning/issues/3184) into account the various build changes we have defined, from recent issues.
