### ISSUE TITLE
Add 'data_append' programmatic interface (API)

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/machine-learning#2146]
We will create the necessary api to allow users to append a new dataset, to an already existing dataset (in an SQL database), via a programmatic-interface, instead of a standalone web HTML5 interface.

**Comment by jeff1evesque** [comment]
We run our defined unit-test from `pytest_session.py`, from a dedicated terminal:

```bash
vagrant@vagrant-ubuntu-trusty-64:/vagrant/test$ py.test
============================= test session starts ==============================

platform linux2 -- Python 2.7.6, pytest-2.8.0, py-1.4.30, pluggy-0.3.1
rootdir: /vagrant/test, inifile: pytest.ini
collected 2 items

programmatic_interface/pytest_session.py .F

=================================== FAILURES ===================================

______________________________ check_data_append _______________________________


    def check_data_append():
        """@check_data_append

        This method tests the 'data_append' session.

        """

>       assert requests.post(endpoint_url, headers=headers, data=get_sample_json
('sample-data-append.json'))
E       assert <Response [500]>
E        +  where <Response [500]> = <function post at 0x7fa6745deed8>('http://l
ocalhost:5000/load-data/', headers={'Content-Type': 'application/json'}, data='{
"properties": {"svm_title": "sample_title", "svm_dataset_type": "json_string", "
svm_session": "data_append"}, "datas...": 235, "indep-variable-5": 64.45, "indep
-variable-2": 92.22, "indep-variable-3": 0.356, "indep-variable-1": 24.32}]}}')
E        +    where <function post at 0x7fa6745deed8> = requests.post
E        +    and   '{"properties": {"svm_title": "sample_title", "svm_dataset_t
ype": "json_string", "svm_session": "data_append"}, "datas...": 235, "indep-vari
able-5": 64.45, "indep-variable-2": 92.22, "indep-variable-3": 0.356, "indep-var
iable-1": 24.32}]}}' = get_sample_json('sample-data-append.json')

programmatic_interface/pytest_session.py:64: AssertionError
====================== 1 failed, 1 passed in 0.45 seconds ======================
```

then, we inspect the corresponding output, on the second terminal window, manually running `app.py`:

```bash
127.0.0.1 - - [02/Oct/2015 15:07:10] "POST /load-data/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/interface/views.py", line 41, in load_data
    elif session_type == 'data_append': response = loader.load_data_append()
  File "/vagrant/brain/load_data.py", line 62, in load_data_append
    session_id = self.data['data']['settings']['svm_session_id']
KeyError: 'svm_session_id'
```
