### ISSUE TITLE
Condense variables into hashes in 'compile_asset.pp'

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/machine-learning#2294]
We need to condense the following variables into puppet's (nested) [hash](https://docs.puppetlabs.com/puppet/latest/reference/lang_data_hash.html) data type:

```puppet
...
## variables: the order of the following array variables are important
$compilers       = ['uglifyjs', 'browserify', 'sass', 'imagemin']
$directory_src   = ['js', 'jsx', 'scss', 'img']
$directory_asset = ['js', 'js', 'css', 'img']
...
```

This will make the `js`, `img` element not seem redundant between `$directory_src`, and `$directory_asset`.  Also, the hash implementation, will remove the idea that order matters between the above arrays.  Finally, we need to correctly iterate the corresponding puppet hash within `compile_asset.pp`.

**Note:** if necessary, we can implemented nested iteration.

**Comment by jeff1evesque** [comment]
Without the suggested fix, a `vagrant up` yields the following error traceback:

```bash
...
==> default: Get:20 http://archive.ubuntu.com trusty-updates/universe Translation-en [173 kB]
==> default: Hit http://archive.ubuntu.com trusty Release
==> default: Get:21 http://archive.ubuntu.com trusty/main Sources [1,064 kB]
==> default: Get:22 http://archive.ubuntu.com trusty/universe Sources [6,399 kB]

==> default: Hit http://archive.ubuntu.com trusty/main amd64 Packages
==> default: Hit http://archive.ubuntu.com trusty/universe amd64 Packages
==> default: Hit http://archive.ubuntu.com trusty/main Translation-en
==> default: Hit http://archive.ubuntu.com trusty/universe Translation-en
==> default: Ign http://archive.ubuntu.com trusty/main Translation-en_US
==> default: Ign http://archive.ubuntu.com trusty/universe Translation-en_US
==> default: Fetched 10.5 MB in 37s (279 kB/s)
==> default: Reading package lists...
==> default: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: The following packages were automatically installed and are no longer required:
==> default:   libdrm-intel1 libdrm-nouveau2 libdrm-radeon1 libfontenc1 libgl1-mesa-dri
==> default:   libgl1-mesa-glx libglapi-mesa libice6 libllvm3.4 libpciaccess0 libpixman-1-0
==> default:   libsm6 libtxc-dxtn-s2tc0 libx11-xcb1 libxaw7 libxcb-dri2-0 libxcb-dri3-0
==> default:   libxcb-glx0 libxcb-present0 libxcb-sync1 libxcomposite1 libxdamage1
==> default:   libxfixes3 libxfont1 libxkbfile1 libxmu6 libxpm4 libxrandr2 libxrender1
==> default:   libxshmfence1 libxt6 libxxf86vm1 ruby-rgen ruby-safe-yaml x11-common
==> default:   x11-xkb-utils xfonts-base xfonts-encodings xfonts-utils xserver-common
==> default:   xserver-xorg-core
==> default: Use 'apt-get autoremove' to remove them.
==> default: The following extra packages will be installed:
==> default:   hiera puppet-common
==> default: Suggested packages:
==> default:   puppet-el vim-puppet ruby-selinux libselinux-ruby1.8 librrd-ruby1.9.1
==> default:   librrd-ruby1.8
==> default: The following packages will be REMOVED:
==> default:   ruby-hiera
==> default: The following NEW packages will be installed:
==> default:   hiera
==> default: The following packages will be upgraded:
==> default:   puppet puppet-common
==> default: 2 upgraded, 1 newly installed, 1 to remove and 137 not upgraded.
==> default: Need to get 1,290 kB of archives.
==> default: After this operation, 3,420 kB of additional disk space will be used.
==> default: Get:1 http://apt.puppetlabs.com/ trusty/main puppet all 3.8.4-1puppetlabs1 [9,310 B]
==> default: Get:2 http://apt.puppetlabs.com/ trusty/main puppet-common all 3.8.4-1puppetlabs1 [1,268 kB]
==> default: Get:3 http://apt.puppetlabs.com/ trusty/main hiera all 1.3.4-1puppetlabs1 [12.0 kB]
==> default: dpkg-preconfigure: unable to re-open stdin: No such file or directory
==> default: Fetched 1,290 kB in 0s (4,008 kB/s)
==> default: (Reading database ... 86445 files and directories currently installed.)
==> default: Preparing to unpack .../puppet_3.8.4-1puppetlabs1_all.deb ...
==> default:  * Stopping puppet agent
==> default:    ...done.
==> default: Unpacking puppet (3.8.4-1puppetlabs1) over (3.4.3-1ubuntu1.1) ...
==> default: Preparing to unpack .../puppet-common_3.8.4-1puppetlabs1_all.deb ...
==> default: Unpacking puppet-common (3.8.4-1puppetlabs1) over (3.4.3-1ubuntu1.1) ...
==> default: dpkg: warning: unable to delete old directory '/etc/ldap/schema': Directory not empty
==> default: Processing triggers for ureadahead (0.100.0-16) ...
==> default: Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
==> default: (Reading database ... 86952 files and directories currently installed.)
==> default: Removing ruby-hiera (1.3.0-1) ...
==> default: Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
==> default: Selecting previously unselected package hiera.
==> default: (Reading database ... 86929 files and directories currently installed.)
==> default: Preparing to unpack .../hiera_1.3.4-1puppetlabs1_all.deb ...
==> default: Unpacking hiera (1.3.4-1puppetlabs1) ...
==> default: Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
==> default: Setting up hiera (1.3.4-1puppetlabs1) ...
==> default: Setting up puppet-common (3.8.4-1puppetlabs1) ...
==> default: Installing new version of config file /etc/puppet/puppet.conf ...
==> default: Installing new version of config file /etc/logcheck/ignore.d.server/puppet-common ...
==> default: Setting up puppet (3.8.4-1puppetlabs1) ...
==> default: Installing new version of config file /etc/init.d/puppet ...
==> default:  * Starting puppet agent
==> default: puppet not configured to start, please edit /etc/default/puppet to enable
==> default:    ...done.
==> default: Processing triggers for ureadahead (0.100.0-16) ...
==> default: Running provisioner: puppet...
==> default: Running Puppet with install_packages.pp...
==> default: stdin: is not a tty
==> default: Warning: Setting templatedir is deprecated. See http://links.puppetlabs.com/env-settings-deprecations
==> default:    (at /usr/lib/ruby/vendor_ruby/puppet/settings.rb:1139:in `issue_deprecation_warning')
==> default: Warning: Config file /etc/puppet/hiera.yaml not found, using Hieradefaults
==> default: Notice: Compiled catalog for vagrant-ubuntu-trusty-64.home in environment production in 1.84 seconds
==> default: Notice: /Stage[main]/Main/Exec[enable-multiverse-repository-2]/returns: executed successfully
==> default: Notice: /Stage[main]/Main/Package[redis-server]/ensure: ensure changed 'purged' to 'present'
==> default: Notice: /Stage[main]/Main/Exec[enable-multiverse-repository-1]/returns: executed successfully
==> default: Notice: /Stage[main]/Python/Package[python-setuptools]/ensure: ensure changed 'purged' to 'present'
==> default: Notice: /Stage[main]/Python/Package[python-pip]/ensure: ensure changed 'purged' to 'present'
==> default: Notice: /Stage[main]/Apt/Apt::Setting[conf-update-stamp]/File[/etc/apt/apt.conf.d/15update-stamp]/content: content changed '{md5}b9de0ac9e2c9854b1bb213e362dc4e41' to '{md5}12bcd8b4e91e9d715290ae16ba3c85fb'
==> default: Notice: /Stage[main]/Apt/File[preferences]/ensure: created
==> default: Notice: /Stage[main]/Main/Exec[build-package-dependencies-1]: Triggered 'refresh' from 2 events
==> default: Notice: /Stage[main]/Main/Package[dos2unix]/ensure: ensure changed 'purged' to 'present'
==> default: Notice: /Stage[main]/Main/Package[ruby-dev]/ensure: ensure changed 'purged' to 'present'
==> default: Notice: /Stage[main]/Main/Package[inotify-tools]/ensure: ensure changed 'purged' to 'present'
==> default: Notice: /Stage[main]/Main/Package[xmltodict]/ensure: created
==> default: Notice: /Stage[main]/Main/Package[redis]/ensure: created
==> default: Notice: /Stage[main]/Main/Package[jsonschema]/ensure: created
==> default: Notice: /Stage[main]/Nodejs::Repo::Nodesource::Apt/Apt::Source[nodesource]/Apt::Key[Add key: 9FD3B784BC1C6FC31A8A0A1C1655A0AB68576280 from Apt::Source nodesource]/Apt_key[Add key: 9FD3B784BC1C6FC31A8A0A1C1655A0AB68576280 from Apt::Source nodesource]/ensure: created
==> default: Notice: /Stage[main]/Nodejs::Repo::Nodesource::Apt/Apt::Source[node
source]/Apt::Setting[list-nodesource]/File[/etc/apt/sources.list.d/nodesource.list]/ensure: created
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]: Triggered 'refresh' from 1 events
==> default: Notice: /Stage[main]/Nodejs::Install/Package[nodejs]/ensure: ensure changed 'purged' to 'present'
==> default: Notice: /Stage[main]/Main/Package[uglify-js]/ensure: created
==> default: Notice: /Stage[main]/Main/Package[babel-core]/ensure: created
==> default: Notice: /Stage[main]/Main/Package[babel-preset-es2015]/ensure: created
==> default: Notice: /Stage[main]/Main/Package[browserify]/ensure: created
==> default: Notice: /Stage[main]/Main/Package[babelify]/ensure: created
==> default: Notice: /Stage[main]/Main/Package[babel-preset-react]/ensure: created
==> default: Notice: /Stage[main]/Main/Package[node-sass]/ensure: created
==> default: Notice: /Stage[main]/Main/Package[imagemin]/ensure: created
==> default: Notice: Finished catalog run in 421.02 seconds
==> default: Running provisioner: puppet...
==> default: Running Puppet with install_sklearn.pp...
==> default: stdin: is not a tty
==> default: Warning: Setting templatedir is deprecated. See http://links.puppetlabs.com/env-settings-deprecations
==> default:    (at /usr/lib/ruby/vendor_ruby/puppet/settings.rb:1139:in `issue_deprecation_warning')
==> default: Warning: Config file /etc/puppet/hiera.yaml not found, using Hieradefaults
==> default: Notice: Compiled catalog for vagrant-ubuntu-trusty-64.home in environment production in 0.66 seconds
==> default: Notice: /Stage[main]/Main/File[/vagrant/build/]/ensure: created
==> default: Notice: /Stage[main]/Git/Package[git]/ensure: ensure changed 'purged' to 'present'
==> default: Notice: /Stage[main]/Main/Vcsrepo[/vagrant/build/scikit-learn]/ensure: Creating repository from present
==> default: Notice: /Stage[main]/Main/Vcsrepo[/vagrant/build/scikit-learn]/ensure: created
==> default: Notice: /Stage[main]/Main/Exec[build-sklearn]: Triggered 'refresh'from 1 events
==> default: Notice: /Stage[main]/Main/Exec[install-sklearn]: Triggered 'refresh' from 1 events
==> default: Notice: Finished catalog run in 292.95 seconds
==> default: Running provisioner: puppet...
==> default: Running Puppet with vagrant_mounted.pp...
==> default: stdin: is not a tty
==> default: Warning: Setting templatedir is deprecated. See http://links.puppetlabs.com/env-settings-deprecations
==> default:    (at /usr/lib/ruby/vendor_ruby/puppet/settings.rb:1139:in `issue_deprecation_warning')
==> default: Notice: Compiled catalog for vagrant-ubuntu-trusty-64.home in environment production in 0.81 seconds
==> default: Notice: /Stage[main]/Main/File[vagrant-startup-script]/ensure: created
==> default: Notice: /Stage[main]/Main/Exec[dos2unix-upstart-vagrant]: Triggered 'refresh' from 1 events
==> default: Notice: /Stage[main]/Main/Service[workaround-vagrant-bug-6074]/ensure: ensure changed 'stopped' to 'running'
==> default: Notice: Finished catalog run in 0.14 seconds
==> default: Running provisioner: puppet...
==> default: Running Puppet with setup_database.pp...
==> default: stdin: is not a tty
==> default: Warning: Setting templatedir is deprecated. See http://links.puppetlabs.com/env-settings-deprecations
==> default:    (at /usr/lib/ruby/vendor_ruby/puppet/settings.rb:1139:in `issue_deprecation_warning')
==> default: Warning: Config file /etc/puppet/hiera.yaml not found, using Hieradefaults
==> default: Notice: Compiled catalog for vagrant-ubuntu-trusty-64.home in environment production in 2.93 seconds
==> default: Notice: /Stage[main]/Mysql::Server::Install/Package[mysql-server]/ensure: ensure changed 'purged' to 'present'
==> default: Notice: /Stage[main]/Mysql::Server::Config/File[mysql-config-file]/
content: content changed '{md5}77f15d6c87f9c136c4efcda072017f71' to '{md5}0574089359c965e31cf588a39c0d446d'
==> default: Notice: /Stage[main]/Mysql::Server::Service/File[/var/log/mysql/error.log]/group: group changed 'adm' to 'mysql'
==> default: Notice: /Stage[main]/Mysql::Server::Root_password/Mysql_user[root@localhost]/password_hash: defined 'password_hash' as '*2470C0C06DEE42FD1618BB99005ADCA2EC9D1E19'
==> default: Notice: /Stage[main]/Mysql::Server::Root_password/File[/root/.my.cnf]/ensure: defined content as '{md5}6bfac0e7e9decf8667dfc388be899b33'
==> default: Notice: /Stage[main]/Mysql::Server::Providers/Mysql_user[provisioner@localhost]/ensure: created
==> default: Notice: /Stage[main]/Mysql::Server::Providers/Mysql_database[db_machine_learning]/ensure: created
==> default: Notice: /Stage[main]/Mysql::Server::Providers/Mysql_user[authenticated@localhost]/ensure: created
==> default: Notice: /Stage[main]/Mysql::Server::Providers/Mysql_grant[authenticated@localhost/db_machine_learning.*]/ensure: created
==> default: Notice: /Stage[main]/Mysql::Server::Providers/Mysql_grant[provisioner@localhost/db_machine_learning.*]/ensure: created
==> default: Notice: /Stage[main]/Mysql::Client::Install/Package[mysql_client]/ensure: ensure changed 'purged' to 'present'
==> default: Notice: /Stage[main]/Mysql::Bindings::Python/Package[python-mysqldb]/ensure: ensure changed 'purged' to 'present'
==> default: Notice: /Stage[main]/Main/Exec[create-database-tables]/returns: executed successfully
==> default: Notice: Finished catalog run in 47.98 seconds
==> default: Running provisioner: puppet...
==> default: Running Puppet with start_webserver.pp...
==> default: stdin: is not a tty
==> default: Warning: Setting templatedir is deprecated. See http://links.puppetlabs.com/env-settings-deprecations
==> default:    (at /usr/lib/ruby/vendor_ruby/puppet/settings.rb:1139:in `issue_deprecation_warning')
==> default: Warning: Config file /etc/puppet/hiera.yaml not found, using Hiera defaults
==> default: Notice: Compiled catalog for vagrant-ubuntu-trusty-64.home in environment production in 1.31 seconds
==> default: Notice: /Stage[main]/Main/File[/vagrant/log/]/ensure: created
==> default: Notice: /Stage[main]/Python::Flask/Package[Flask]/ensure: created
==> default: Notice: /Stage[main]/Main/File[server-startup-script]/ensure: created
==> default: Notice: /Stage[main]/Main/Exec[dos2unix-flask]: Triggered 'refresh' from 1 events
==> default: Notice: /Stage[main]/Main/Service[flask]/ensure: ensure changed 'stopped' to 'running'
==> default: Notice: Finished catalog run in 3.12 seconds
==> default: Running provisioner: puppet...
==> default: Running Puppet with configure_system.pp...
==> default: stdin: is not a tty
==> default: Warning: Setting templatedir is deprecated. See http://links.puppetlabs.com/env-settings-deprecations
==> default:    (at /usr/lib/ruby/vendor_ruby/puppet/settings.rb:1139:in `issue_deprecation_warning')
==> default: Warning: Config file /etc/puppet/hiera.yaml not found, using Hiera defaults
==> default: Notice: Compiled catalog for vagrant-ubuntu-trusty-64.home in environment production in 0.60 seconds
==> default: Notice: /Stage[main]/Timezone/File[/etc/timezone]/content: content changed '{md5}4f24b133ba38d8fd565168742c9aedeb' to '{md5}1c48d224744cb3bb3f49a262f508fbaf'
==> default: Notice: /Stage[main]/Timezone/File[/etc/localtime]/content: content changed '{md5}c79354b8dbee09e62bbc3fb544853283' to '{md5}e4ca381035a34b7a852184cc0dd89baa'
==> default: Notice: Finished catalog run in 0.10 seconds
==> default: Running provisioner: puppet...
==> default: Running Puppet with compile_asset.pp...
==> default: stdin: is not a tty
==> default: Warning: Setting templatedir is deprecated. See http://links.puppetlabs.com/env-settings-deprecations
==> default:    (at /usr/lib/ruby/vendor_ruby/puppet/settings.rb:1139:in `issue_deprecation_warning')
==> default: Error: Evaluation Error: Error while evaluating a Resource Statement, Duplicate declaration: File[/vagrant/interface/static/js/] is already declared in file /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3/compile_asset.pp:16; cannot redeclare at /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3/compile_asset.pp:16 at /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3/compile_asset.pp:16:5 on node vagrant-ubuntu-trusty-64.home
==> default: Error: Evaluation Error: Error while evaluating a Resource Statement, Duplicate declaration: File[/vagrant/interface/static/js/] is already declared in file /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3/compile_asset.pp:16; cannot redeclare at /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3/compile_asset.pp:16 at /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3/compile_asset.pp:16:5 on node vagrant-ubuntu-trusty-64.home
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by jeff1evesque** [comment]
ac38734: now a `vagrant up`, yields the following error traceback:

```bash
...
==> default: Running provisioner: puppet...
==> default: Running Puppet with compile_asset.pp...
==> default: stdin: is not a tty
==> default: Warning: Setting templatedir is deprecated. See http://links.puppetlabs.com/env-settings-deprecations
==> default:    (at /usr/lib/ruby/vendor_ruby/puppet/settings.rb:1139:in `issue_deprecation_warning')
==> default: Error: Evaluation Error: Error while evaluating a Method call, lambda called with mis-matched arguments
==> default: expected:
==> default:   lambda(Integer index, String compiler) - arg count {2}
==> default: actual:
==> default:   lambda(String, Struct[{'src'=>String, 'asset'=>String}]) - arg count {2} at /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3/compile_asset.pp:25:11 on node vagrant-ubuntu-trusty-64.home
==> default: Error: Evaluation Error: Error while evaluating a Method call, lambda called with mis-matched arguments
==> default: expected:
==> default:   lambda(Integer index, String compiler) - arg count {2}
==> default: actual:
==> default:   lambda(String, Struct[{'src'=>String, 'asset'=>String}]) - arg count {2} at /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3/compile_asset.pp:25:11 on node vagrant-ubuntu-trusty-64.home
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by jeff1evesque** [comment]
df06ada: now a `vagrant up`, yields the following error traceback:

```bash
...
==> default: Running provisioner: puppet...
==> default: Running Puppet with compile_asset.pp...
==> default: stdin: is not a tty
==> default: Warning: Setting templatedir is deprecated. See http://links.puppetlabs.com/env-settings-deprecations
==> default:    (at /usr/lib/ruby/vendor_ruby/puppet/settings.rb:1139:in `issue_deprecation_warning')
==> default: Error: Evaluation Error: Error while evaluating a Method call, lambda called with mis-matched arguments
==> default: expected:
==> default:   lambda(Integer index, Hash[Scalar, Data] compiler) - arg count {2}
==> default: actual:
==> default:   lambda(String, Struct[{'src'=>String, 'asset'=>String}]) - arg count {2} at /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3/compile_asset.pp:25:11 on node vagrant-ubuntu-trusty-64.home
==> default: Error: Evaluation Error: Error while evaluating a Method call, lambda called with mis-matched arguments
==> default: expected:
==> default:   lambda(Integer index, Hash[Scalar, Data] compiler) - arg count {2}
==> default: actual:
==> default:   lambda(String, Struct[{'src'=>String, 'asset'=>String}]) - arg count {2} at /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3/compile_asset.pp:25:11 on node vagrant-ubuntu-trusty-64.home
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by jeff1evesque** [comment]
d3b64c9: now a `vagrant up`, yields the following error traceback:

```bash
...
==> default: Running provisioner: puppet...
==> default: Running Puppet with compile_asset.pp...
==> default: stdin: is not a tty
==> default: Warning: Setting templatedir is deprecated. See http://links.puppetlabs.com/env-settings-deprecations
==> default:    (at /usr/lib/ruby/vendor_ruby/puppet/settings.rb:1139:in `issue_deprecation_warning')
==> default: Error: Evaluation Error: Error creating type specialization of a Service-Type, Cannot use Hash[String, String] where a resource title String is expected at /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3/compile_asset.pp:67:32 on node vagrant-ubuntu-trusty-64.home
==> default: Error: Evaluation Error: Error creating type specialization of a Service-Type, Cannot use Hash[String, String] where a resource title String is expected at /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3/compile_asset.pp:67:32 on node vagrant-ubuntu-trusty-64.home
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
