### ISSUE TITLE
Error: Cannot find module 'babelify'

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/machine-learning#2309]
Our `browserify_execution.log` generates the following error traceback, after an initial `vagrant up`:

```bash
+ read -r file
Setting up watches.
Watches established.
...
+ filename=select_session
+ browserify /vagrant/src/jsx/select_session.jsx -t '[' babelify --presets es2015,react ']' -o /vagrant/src/js/select_session.js
Error: Cannot find module 'babelify' from '/vagrant/puppet/scripts'
    at /usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at Object.oncomplete (fs.js:108:15)
```

**Comment by jeff1evesque** [comment]
We see our npm modules are installed:

```bash
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ whereis node_modules
node_modules: /usr/lib/node_modules
```

**Comment by jeff1evesque** [comment]
The committed solution still generates the following in `browserify_execution.log`:

```bash
+ read -r file
Setting up watches.
Watches established.
...
+ filename=select_session
+ browserify /vagrant/src/jsx/select_session.jsx -t '[' babelify --presets es2015,react ']' -o /vagrant/src/js/select_session.js
Error: Couldn't find preset "es2015" relative to directory "/vagrant/src/jsx" while parsing file: /vagrant/src/jsx/select_session.jsx
    at OptionManager.mergePresets (/usr/lib/node_modules/babelify/node_modules/babel-core/lib/transformation/file/options/option-manager.js:327:17)
    at OptionManager.mergeOptions (/usr/lib/node_modules/babelify/node_modules/babel-core/lib/transformation/file/options/option-manager.js:287:12)
    at OptionManager.init (/usr/lib/node_modules/babelify/node_modules/babel-core/lib/transformation/file/options/option-manager.js:416:10)
    at File.initOptions (/usr/lib/node_modules/babelify/node_modules/babel-core/lib/transformation/file/index.js:190:75)
    at new File (/usr/lib/node_modules/babelify/node_modules/babel-core/lib/transformation/file/index.js:121:22)
    at Pipeline.transform (/usr/lib/node_modules/babelify/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
    at Babelify._flush (/usr/lib/node_modules/babelify/index.js:28:24)
    at Babelify.<anonymous> (_stream_transform.js:130:12)
    at Babelify.g (events.js:180:16)
    at Babelify.emit (events.js:117:20)
```

**Comment by jeff1evesque** [comment]
We need to convert `$packages_general_npm` as a hash type.  Specifically, we will attempt to implement:

```puppet
...
$packages_general_npm = {
    uglify-js => { default_dir => true }
    imagemin => { default_dir => true }
    node-sass => { default_dir => true }
    babel-core => { default_dir => true }
    browserify => {default_dir => true }
    babelify => { default_dir => true }
    babel-preset-es2015 => { default_dir => false, custom_dir => '/path/to/install/module' }
    babel-preset-react => { default_dir => false, custom_dir => '/path/to/install/module' }
}
...
```

Then, we will be able to iterate the hash, and implement the [`install_options`](https://docs.puppetlabs.com/references/latest/type.html#package-attribute-install_options):

```puppet
...
$packages_general_npm.each |String $package, Hash $resource| {
    ## packages: install general packages (npm)
    package {$package:
        ensure   => 'present',
        provider => 'npm',
        require  => Package['npm'],
        if (! $resource['default_dir']) {
            install_options => [ '/S', { 'INSTALLDIR' => $resource['custom_dir'] } ],
        }
    }
}
...
```

**Comment by jeff1evesque** [comment]
The following npm [documentation](https://docs.npmjs.com/files/folders#prefix-configuration) states:

>When the global flag is set, npm installs things into this prefix. When it is not set, it uses the root of the current package, or the current working directory if not in a package already.

Therefore, we need to add the `-g` flag, to ensure that the `--prefix` properly works.

**Comment by jeff1evesque** [comment]
We will forgo the [above](https://github.com/jeff1evesque/machine-learning/issues/2309#issuecomment-162957705) idea of hash iteration.  Instead, we will implement a `/vagrant/src/jsx/package.json`.  This file will define npm packages related to browserify, and babelify.  Specifically, the contents of `/vagrant/src/jsx/package.json` will install the necessary packages via:

```bash
$ cd /vagrant/src/jsx
$ npm install)
```

To add packages to the build definition within `package.json`:

```bash
$ cd /vagrant/src/jsx
$ npm install [package1] [package2] --save)
```

**Note:** we will need to [update](https://github.com/jeff1evesque/machine-learning/issues/2311) both npm, and nodejs, before the above can be approached.

**Comment by jeff1evesque** [comment]
A manual install on the vagrant vm, generates a *protocol error* symlink error:

```bash
vagrant@vagrant-ubuntu-trusty-64:/vagrant/src/jsx$ npm install babel-preset-es2
015 --save
reactjs@1.0.0 /vagrant/src/jsx
├── babel-code-frame@6.3.13  extraneous
├── babel-generator@6.3.17  extraneous
├── babel-helpers@6.3.13  extraneous
├── babel-plugin-check-es2015-constants@6.3.13  extraneous
├── babel-plugin-syntax-async-functions@6.3.13  extraneous
├── babel-plugin-transform-es2015-arrow-functions@6.3.13  extraneous
├── babel-plugin-transform-es2015-block-scoped-functions@6.3.13  extraneous
├── babel-plugin-transform-es2015-block-scoping@6.3.13  extraneous
├── babel-plugin-transform-es2015-computed-properties@6.3.13  extraneous
├── babel-plugin-transform-es2015-destructuring@6.3.15  extraneous
├── babel-plugin-transform-es2015-for-of@6.3.13  extraneous
├── babel-plugin-transform-es2015-function-name@6.3.13  extraneous
├── babel-plugin-transform-es2015-literals@6.3.13  extraneous
├── babel-plugin-transform-es2015-modules-commonjs@6.3.16  extraneous
├── babel-plugin-transform-es2015-object-super@6.3.13  extraneous
├── babel-plugin-transform-es2015-parameters@6.3.13  extraneous
├── babel-plugin-transform-es2015-shorthand-properties@6.3.13  extraneous
├── babel-plugin-transform-es2015-spread@6.3.14  extraneous
├── babel-plugin-transform-es2015-sticky-regex@6.3.13  extraneous
├── babel-plugin-transform-es2015-template-literals@6.3.13  extraneous
├── babel-plugin-transform-es2015-typeof-symbol@6.3.13  extraneous
├── babel-plugin-transform-es2015-unicode-regex@6.3.13  extraneous
├── babel-register@6.3.13  extraneous
├── convert-source-map@1.1.2  extraneous
├── debug@2.2.0  extraneous
├── globals@8.14.0  extraneous
├── invariant@2.2.0  extraneous
├── json5@0.4.0  extraneous
├── minimatch@2.0.10  extraneous
├── path-is-absolute@1.0.0  extraneous
├── shebang-regex@1.0.0  extraneous
└── slash@1.0.0  extraneous

npm WARN EPACKAGEJSON reactjs@1.0.0 No repository field.
npm WARN EPACKAGEJSON reactjs@1.0.0 license should be a valid SPDX license expre
ssion
npm ERR! Linux 3.13.0-55-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "babel-preset-es2015" "
--save"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! path ../babylon/bin/babylon.js
npm ERR! code EPROTO
npm ERR! errno -71
npm ERR! syscall symlink

npm ERR! EPROTO: protocol error, symlink '../babylon/bin/babylon.js' -> '/vagran
t/src/jsx/node_modules/.bin/babylon'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 3.13.0-55-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "babel-preset-es2015" "
--save"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! path npm-debug.log.e34791dd7971bf7b36ccb58939fe01eb
npm ERR! code ETXTBSY
npm ERR! errno -26
npm ERR! syscall rename

npm ERR! ETXTBSY: text file is busy, rename 'npm-debug.log.e34791dd7971bf7b36ccb
58939fe01eb' -> 'npm-debug.log'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/src/jsx/npm-debug.log
```

This means we need to include the `--no-bin-links` flag, as follows:

```bash
$ cd /vagrant/src/jsx
$ npm install --no-bin-links [package1] [package2] --save
```

**Comment by jeff1evesque** [comment]
We need to add the `--no-bin-links` flag with the `npm install` command, within the `install_packages.pp`.
