### ISSUE TITLE
Refactor 'html_form.js' using reactjs framework

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/machine-learning#2332]
We will refactor [`html_form.js`](https://github.com/jeff1evesque/machine-learning/blob/ec8bbe9a3a13e7fadd7bef055bf56abff02a916f/src/js/html_form.js), using the [reactjs](https://facebook.github.io/react/) framework.  The [tie-breaker](https://www.airpair.com/angularjs/posts/angular-vs-react-the-tie-breaker) between [angularjs](https://angularjs.org/), and [reactjs](https://facebook.github.io/react/), were largely considered in a previous [issue](https://github.com/jeff1evesque/machine-learning/issues/2094#issuecomment-159763203), when considering the former.

**Comment by jeff1evesque** [comment]
An initial approach can be as follows:

- convert each `if`, `else if` statements to being separate react components
- take the code inside jquery `.on` events, and wrap them into method definitions
  - these method definitions would be implemented within the corresponding reactjs component

**Comment by jeff1evesque** [comment]
**IRC #reactjs (12/16/15 ~ 10:15m EST):**

>CedarsHope: React's a different ballgame to straight up jquery DOM manipulation, there's a few concepts to grasp... JSX, virtual doms, diffing, controlled and uncontrolled components

>jeffreylevesque: how do i enable vdom?

>CedarsHope: Basically react and jquery don't mix without a little work... it's not wise to have jQuery manipulating the DOM, when you make a react component, it becomes react's job to handle DOM changes from that point forward

>jeffreylevesque: i will give this a pass through, and try to break it up as you suggest

>CedarsHope: when you write a component in JSX, react produces a VDOM of that component from it's render method
CedarsHope: well.. JSX isn't necessary, rather, when you use react in general... but that's nitpicking

>jeffreylevesque: so, jsx components are the key pieces to virtualdom?

>CedarsHope: in a way, yes
CedarsHope: your render method produces an in memory representation of the DOM, called the virtual DOM, based on the component state and props (whichever combination you use in your render method)
CedarsHope: then everytime you set state, the render method is ran again, and produces a new VDOM
CedarsHope: react compares the new VDOM to the old, and finds the differences, and applys those changes to the real DOM
CedarsHope: applies*
CedarsHope: that's why jQuery shouldn't really meddle when it's react's job jeffreylevesque_
CedarsHope: there are react components that wrap jquery plugins, but that's more of a convenience for encapsulation

**Comment by jeff1evesque** [comment]
We can break up our current `html_form.js` into multiple `jsx` templates.  Then, we can have a skeleton `html_form.jsx` template, implementing the `require()` method, to require the latter templates via `browserify`:

**IRC #reactjs (12/17/15 ~ 8:45pm EST):**

>jeffreylevesque: I'm using reactjs: how can i `require / include` another js file (the compiled jsx file) in a js file?  ReactJS uses npm
jeffreylevesque: do i have to do `require / include` equivalent from the jsx template, or can it be done in js file - and, if i do some kind of require logic, does it need to be compiled to plain js?

>solenoids: jeffreylevesque: are you using browserify?
solenoids	if not, start using it
solenoids	you can call require('./otherfile') using browserify to import other files, just like in node

>jeffreylevesque: solenoids: yes sir, i'm using browserify
jeffreylevesque: but, jquery can do it natively?

>solenoids: jquery might have module loading functionality, but if you're already using browserify, it's a superior way to do it when using react
solenoids: jquery's not very useful in react projects, the newer tooling and libraries out there works much nicer with react

>jeffreylevesque: so i need to choose either to put the require logic in js, and switch the uglifyjs to browserify, or i need to put it into the jsx templates

>solenoids: uglifyjs and browserify are different tools
solenoids: browserify implements `require` for the browser and lets you bundle up multiple file projects into one file that can run in a <script> tag

**Comment by jeff1evesque** [comment]
We need to fix the following implementations:

- `/src/jsx/require/supply_dataset_file.jsx`
- `/src/jsx/require/supply_dataset_url.jsx`

**Comment by jeff1evesque** [comment]
We will consider implementing the `babel-register` package, which allows modules being *required* to be automatically *transpiled*.

**Comment by jeff1evesque** [comment]
When we remove all `require()` statements from [`html_form.jsx`](https://github.com/jeff1evesque/machine-learning/blob/748bcc9092d81882d798aff53575f2cb3e29be62/src/jsx/html_form.jsx), the [browserify](https://github.com/jeff1evesque/machine-learning/blob/748bcc9092d81882d798aff53575f2cb3e29be62/puppet/scripts/browserify#L31) command compiles `html_form.jsx` into `html_form.min.js`, as follows:

```javascript
!function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a="function"==typeof require&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}for(var i="function"==typeof require&&require,o=0;o<r.length;o++)s(r[o]);return s}({1:[function(require,module,exports){"use strict";$(document).ready(function(){function buildForm(selector,data,arrRemove){$(".svm-form-submit").remove(),$("form "+selector).parent().nextAll().remove(),$("form "+selector).parent().parent().nextAll().remove(),"undefined"!=typeof arrRemove&&$.each(arrRemove,function(key,value){$(value).remove()}),$(selector).after(data)}function fieldDeterminant(element){for(var numElements=element.length,i=0;numElements>i;i++)if(element[i].value.length<1)return!1;return!0}$(".fieldset-session-type").on("change",'select[name="svm_session"]',function(){"model_generate"==$(this).val().toLowerCase()||"model_predict"==$(this).val().toLowerCase()||"data_new"==$(this).val().toLowerCase()||"data_append"==$(this).val().toLowerCase(),buildForm(".fieldset-session-type",null,[".fieldset-session-predict",".fieldset-session-generate",".fieldset-session-data-upload",".svm-form-submit"]),-1!==$.inArray($(this).val(),["data_append","model_generate"])&&sessionId(),-1!==$.inArray($(this).val(),["model_predict"])&&modelId(),$(".fieldset-session-generate").on("change",'select[name="svm_session_id"], select[name="svm_model_type"]',function(){$('select[name="svm_session_id"]').val()&&$('select[name="svm_model_type"]').val()?buildForm(".fieldset-session-generate",null,[".svm_form_submit"]):$(".svm-form-submit").remove()}),$(".fieldset-session-predict").on("change",'select[name="svm_model_id"]',function(){$('select[name="svm_model_id"]').val()?(featureProperties(),$(".fieldset-session-predict").on("change",'input[name="prediction_input[]"]',function(){var flagField=fieldDeterminant($('input[name="prediction_input[]"]'));flagField?buildForm(".fieldset-session-predict",null,[".svm-form-submit"]):(buildForm(".fieldset-session-predict",null,[".svm-form-submit",".fieldset-prediction-result"]),$(".svm-form-submit").remove())})):buildForm(".fieldset-session-predict",null,[".svm-form-submit",".fieldset-prediction-input",".fieldset-prediction-result"])}),$(".fieldset-session-data-upload").on("input change",'select[name="svm_dataset_type"], select[name="svm_session_id"], input[name="svm_title"], select[name="svm_model_type"]',function(){$('select[name="svm_session_id"]').val()&&$('select[name="svm_dataset_type"]').val()?$('select[name="svm_session_id"]').val().length>0&&"file_upload"==$('select[name="svm_dataset_type"]').val().toLowerCase()||$('select[name="svm_session_id"]').val()>0&&"dataset_url"==$('select[name="svm_dataset_type"]').val().toLowerCase():$('select[name="svm_dataset_type"]').val()&&$('input[name="svm_title"]').val()&&("file_upload"==$('select[name="svm_dataset_type"]').val().toLowerCase()&&0!==$('input[name="svm_title"]').val().length||"dataset_url"==$('select[name="svm_dataset_type"]').val().toLowerCase()&&0!==$('input[name="svm_title"]').val().length),buildForm(".fieldset-dataset-type",null,[".fieldset-training-parameters",".fieldset-training-type",".fieldset-supply-dataset"]),$(".fieldset-supply-dataset").on("change",'input[name="svm_dataset[]"]',function(){var flagField=fieldDeterminant($('input[name="svm_dataset[]"]'));flagField?buildForm(".fieldset-session-data-upload",null,[".svm-form-submit"]):$(".svm-form-submit").remove()})})})})},{}]},{},[1]);
```

**Comment by jeff1evesque** [comment]
Our webform loads correctly, initially:

![initial-webform](https://cloud.githubusercontent.com/assets/2907085/12108046/a6ee8334-b340-11e5-801e-f86b50e13fbe.PNG)

After, selecting a *session type*, errors can be seen within the browser console:

![final-webform](https://cloud.githubusercontent.com/assets/2907085/12108069/fc20a116-b340-11e5-8b5b-0e491fe7eb78.PNG)

**Comment by jeff1evesque** [comment]
Our webform still loads correctly, initially:

![initial-webform](https://cloud.githubusercontent.com/assets/2907085/12130366/d272af3e-b3d7-11e5-9569-e308d495f856.PNG)

After, selecting any *session type*, errors can be seen within the browser console:

![final-webform](https://cloud.githubusercontent.com/assets/2907085/12130383/eed00794-b3d7-11e5-833e-c3853a548a9f.PNG)

**Comment by jeff1evesque** [comment]
**IRC #reactjs (01/05/16 ~ 6:30pm EST):**

>jeffreylevesque: what's the difference between `ReactDOM.render()`, and `React.render()`?

>chenghiz: render is a method of ReactDOM now (in 0.14), not React

**Comment by jeff1evesque** [comment]
An initial `vagrant up` build generates the following within `browserify_execution.log`:

```bash
+ cat /dev/null
+ inotifywait /Setting up watches.
Watches established.
+ filename=README
+ file_extension=md
+ '[' md = jsx ']'
+ read -r file
+ filename=html_form
+ file_extension=jsx
+ '[' jsx = jsx ']'
+ cd /usr/lib/node_modules
+ browserify /vagrant/src/jsx/html_form.jsx -t '[' babelify --presets es2015,react ']' -o /vagrant/src/js/html_form.js
SyntaxError: /vagrant/src/jsx/html_form.jsx: 'import' and 'export' may only appear at the top level (11:2)
   9 | 
  10 |   // ReactJS variables
> 11 |   import ModelGenerate from './require/model_generate.jsx';
     |   ^
  12 |   import ModelPredict from './require/model_predict.jsx';
  13 |   import DataNew from './require/data_new.jsx';
  14 |   import DataAppend from './require/data_append.jsx';
    at Parser.pp.raise (/usr/lib/node_modules/babelify/node_modules/babylon/index.js:1413:13)
    at Parser.pp.parseStatement (/usr/lib/node_modules/babelify/node_modules/babylon/index.js:1909:16)
    at Parser.<anonymous> (/usr/lib/node_modules/babelify/node_modules/babylon/index.js:3563:22)
    at Parser.parseStatement (/usr/lib/node_modules/babelify/node_modules/babylon/index.js:3563:22)
    at Parser.pp.parseBlockBody (/usr/lib/node_modules/babelify/node_modules/babylon/index.js:2282:21)
    at Parser.pp.parseBlock (/usr/lib/node_modules/babelify/node_modules/babylon/index.js:2263:8)
    at Parser.pp.parseFunctionBody (/usr/lib/node_modules/babelify/node_modules/babylon/index.js:1122:22)
    at Parser.<anonymous> (/usr/lib/node_modules/babelify/node_modules/babylon/index.js:3550:20)
    at Parser.parseFunctionBody (/usr/lib/node_modules/babelify/node_modules/babylon/index.js:3550:20)
    at Parser.pp.parseFunction (/usr/lib/node_modules/babelify/node_modules/babylon/index.js:2394:8)
+ echo html_form.js
+ read -r file
+ filename=package
+ file_extension=json
+ '[' json = jsx ']'
+ read -r file
+ filename=select_session
+ file_extension=jsx
+ '[' jsx = jsx ']'
+ cd /usr/lib/node_modules
+ browserify /vagrant/src/jsx/select_session.jsx -t '[' babelify --presets es2015,react ']' -o /vagrant/src/js/select_session.js
+ echo select_session.js
+ read -r file
```

**Comment by jeff1evesque** [comment]
We are now getting the following error, when making an initial selection within the webform:

>Uncaught Error: Invariant Violation: _registerComponent(...): Target container is not a DOM element.

![not-dom-element](https://cloud.githubusercontent.com/assets/2907085/12226829/37199242-b7f0-11e5-8d2c-2852d1b9d46d.PNG)

**Comment by jeff1evesque** [comment]
We are still getting the above `Uncaught Error`, with the exception when `data_new` is selected, we get the following error traceback:

```
Uncaught ReferenceError: DateNew is not defined
```

**Comment by jeff1evesque** [comment]
Even though `.fieldset-dataset-type` element exists within the DOM, the following command entered via the browser console, suggests the element does not exist:

```
> console.log(document.querySelector('.fieldset-dataset-type'));
null
undefined
```

![console-null](https://cloud.githubusercontent.com/assets/2907085/12304939/30739a98-ba00-11e5-98bf-14c6ea443bbd.PNG)

**Comment by jeff1evesque** [comment]
We need to consider moving the logic associated with creating the following session-type fieldsets, into [`select_session.jsx`](https://github.com/jeff1evesque/machine-learning/blob/b69c44504b0003e43e73690591e6d95506bb8150/src/jsx/require/select_session.jsx#L19):

- model_generate
- model_predict
- data_new
- data_append

Specifically, we will import the associated template files within `select_session.jsx`, and possibly move corresponding event handling logic, too.

**Comment by jeff1evesque** [comment]
We may need to implement, or combine the following approaches:

- [nested components](http://nguyenthethang.com/2015/07/10/a-journey-with-reactjs-create-nseted-components-with-jsx/) with jsx templating
  - https://jsfiddle.net/69z2wepo/11700/

**Comment by jeff1evesque** [comment]
We are only allow to have one [root node](https://facebook.github.io/react/tips/maximum-number-of-jsx-root-nodes.html).  This means, the following:

```reactjs
...
    render: function(){
        var SupplyDataset = this.getSupplyDataset();
        return(
            <fieldset className='fieldset-session-data-upload'>
                <legend>Data Upload</legend>
                <fieldset className='fieldset-dataset-type'>
                    <legend>Configurations</legend>
                    <p>Please save the <i>Session Name</i>, then provide dataset type</p>
                    <input type='text' name='svm_title' placeholder='Session Name' onChange={this.changeTitle} value={this.state.value_title} />
                    <select name='svm_dataset_type' autoComplete='off' onChange={this.changeDatasetType} value={this.state.value_dataset_type}>
                        <option value='' defaultValue>--Select--</option>
                        <option value='file_upload'>Upload file</option>
                        <option value='dataset_url'>Dataset URL</option>
                    </select>
                </fieldset>
            </fieldset>

            <SupplyDataset/>
        );
    },
...
```

needs to be adjusted to the following pattern:

```reactjs
...
    render: function(){
        var SupplyDataset = this.getSupplyDataset();
        return(
            <fieldset className='fieldset-session-data-upload'>
                <legend>Data Upload</legend>
                <fieldset className='fieldset-dataset-type'>
                    <legend>Configurations</legend>
                    <p>Please save the <i>Session Name</i>, then provide dataset type</p>
                    <input type='text' name='svm_title' placeholder='Session Name' onChange={this.changeTitle} value={this.state.value_title} />
                    <select name='svm_dataset_type' autoComplete='off' onChange={this.changeDatasetType} value={this.state.value_dataset_type}>
                        <option value='' defaultValue>--Select--</option>
                        <option value='file_upload'>Upload file</option>
                        <option value='dataset_url'>Dataset URL</option>
                    </select>
                </fieldset>

                <SupplyDataset/>
            </fieldset>
        );
    },
...
```

**Comment by jeff1evesque** [comment]
Below suggests either the `<SupplyDataset/>` component is not rendering, or `this.state.value_dataset_type` is null:

![missing](https://cloud.githubusercontent.com/assets/2907085/12379686/f9bd7070-bd2c-11e5-9042-6510697e8d66.PNG)

**Comment by jeff1evesque** [comment]
We've temporarily simplified `data_new.jsx` to the following:

```
/**
 * data_new.jsx: append 'data_new' fieldset.
 *
 * @DataNew, must be capitalized in order for reactjs to render it as a
 *     component. Otherwise, the variable is rendered as a dom node.
 *
 * Note: this script implements jsx (reactjs) syntax.
 */

import SupplyDatasetFile from './supply_dataset_file.jsx';
import SupplyDatasetUrl from './supply_dataset_url.jsx';

var DataNew = React.createClass({
  // initial 'state properties'
    getInitialState: function() {
        return {
            value_dataset_type: '--Select--'
        };
    },
  // update 'state properties'
    change: function(event){
        this.setState({
            value_dataset_type: event.target.value_dataset_type
        });
    },
  // triggered when 'state properties' change
    render: function(){
        var SupplyDataset = this.getSupplyDataset(this.state.value_dataset_type);
        return(
            <fieldset className='fieldset-session-data-upload'>
                <legend>Data Upload</legend>
                <fieldset className='fieldset-dataset-type'>
                    <legend>Configurations</legend>
                    <p>Please save the <i>Session Name</i>, then provide dataset type</p>

                    <select name='svm_dataset_type' autoComplete='off' onChange={this.change} value={this.state.value_dataset_type}>
                        <option value='' defaultValue>--Select--</option>
                        <option value='file_upload'>Upload file</option>
                        <option value='dataset_url'>Dataset URL</option>
                    </select>
                </fieldset>

                <SupplyDataset/>
            </fieldset>
        );
    },
  // call back: used for the above 'render' (return 'span' if undefined)
    getSupplyDataset: function(dataset_type) {

            return {
                file_upload: SupplyDatasetFile,
                dataset_url: SupplyDatasetUrl
            }[dataset_type] || 'span';

    }
});

// indicate which class can be exported, and instantiated via 'require'
export default DataNew
```

which, may have defined `this.state.value_dataset_type` as `null`, and thus rendering an empty `<span>` element:

![empty-span](https://cloud.githubusercontent.com/assets/2907085/12398613/c84e5372-bde2-11e5-83ec-4bf0b6a66be8.PNG)

**Comment by jeff1evesque** [comment]
We've temporarily simplified `data_new.jsx` to the following:

```
/**
 * data_new.jsx: append 'data_new' fieldset.
 *
 * @DataNew, must be capitalized in order for reactjs to render it as a
 *     component. Otherwise, the variable is rendered as a dom node.
 *
 * Note: this script implements jsx (reactjs) syntax.
 */

import SupplyDatasetFile from './supply_dataset_file.jsx';
import SupplyDatasetUrl from './supply_dataset_url.jsx';

var DataNew = React.createClass({
  // initial 'state properties'
    getInitialState: function() {
        return {
            value_dataset_type: '--Select--'
        };
    },
  // update 'state properties'
    change: function(event){
        this.setState({
            value_dataset_type: event.target.value_dataset_type
        });
    },
  // triggered when 'state properties' change
    render: function(){
        var SupplyDataset = this.getSupplyDataset(this.state.value_dataset_type);
        console.log(this.state.value_dataset_type);
        return(
            <fieldset className='fieldset-session-data-upload'>
                <legend>Data Upload</legend>
                <fieldset className='fieldset-dataset-type'>
                    <legend>Configurations</legend>
                    <p>Please save the <i>Session Name</i>, then provide dataset type</p>

                    <select name='svm_dataset_type' autoComplete='off' onChange={this.change} value={this.state.value_dataset_type}>
                        <option value='' defaultValue>--Select--</option>
                        <option value='file_upload'>Upload file</option>
                        <option value='dataset_url'>Dataset URL</option>
                    </select>
                </fieldset>

                <SupplyDataset/>
            </fieldset>
        );
    },
  // call back: used for the above 'render' (return 'span' if undefined)
    getSupplyDataset: function(dataset_type) {

            return {
                file_upload: SupplyDatasetFile,
                dataset_url: SupplyDatasetUrl
            }[dataset_type] || 'span';

    }
});

// indicate which class can be exported, and instantiated via 'require'
export default DataNew
```

which verifies `this.state.value_dataset_type` is `null`, via the above subsnippet:

```
...
  // triggered when 'state properties' change
    render: function(){
        var SupplyDataset = this.getSupplyDataset(this.state.value_dataset_type);
        console.log(this.state.value_dataset_type);
...
```

![undefined](https://cloud.githubusercontent.com/assets/2907085/12409041/7f548ac2-be34-11e5-8be1-abb705d2e92b.PNG)

**Comment by jeff1evesque** [comment]
71f9426, 0aba385: some progress was made, such that the *Supply Dataset* fieldset is semi-properly being rendered:

![uploadfile](https://cloud.githubusercontent.com/assets/2907085/12410889/409e7dde-be47-11e5-990e-af47abf4c01e.PNG)

![uploadurl](https://cloud.githubusercontent.com/assets/2907085/12410895/487b1058-be47-11e5-8520-b5bcb080401a.PNG)

However, the semi-correct rendering is only rendering on the selection made on the following:

```
...
                    <select name='svm_dataset_type' autoComplete='off' onChange={this.changeDatasetType} value={this.state.value_dataset_type}>
                        <option value='' defaultValue>--Select--</option>
                        <option value='file_upload'>Upload file</option>
                        <option value='dataset_url'>Dataset URL</option>
                    </select>
...
```

instead of collectively, on the following (both) elements:

```
...
                    <input type='text' name='svm_title' placeholder='Session Name' onChange={this.changeTitle} value={this.state.value} />
                    <select name='svm_dataset_type' autoComplete='off' onChange={this.changeDatasetType} value={this.state.value_dataset_type}>
                        <option value='' defaultValue>--Select--</option>
                        <option value='file_upload'>Upload file</option>
                        <option value='dataset_url'>Dataset URL</option>
                    </select>
...
```

**Comment by jeff1evesque** [comment]
The above commits, resolves the issue regarding rendering the `<SupplyDataset/>` component.

**Comment by jeff1evesque** [comment]
After implementing a *data_new* session:

![data-new](https://cloud.githubusercontent.com/assets/2907085/12527824/347dd448-c151-11e5-95ee-2de5805f873e.PNG)

we verify data exists in corresponding database tables:

```bash
MariaDB [(none)]> use db_machine_learning
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MariaDB [db_machine_learning]> show tables;
+-------------------------------+
| Tables_in_db_machine_learning |
+-------------------------------+
| tbl_dataset_entity            |
| tbl_feature_count             |
| tbl_feature_value             |
| tbl_observation_label         |
+-------------------------------+
4 rows in set (0.00 sec)

MariaDB [db_machine_learning]> select * from tbl_dataset_entity;
+-----------+-------+-------------+---------------------+--------------+-------------------+
| id_entity | title | uid_created | datetime_created    | uid_modified | datetime_modified |
+-----------+-------+-------------+---------------------+--------------+-------------------+
|         1 | test  |           1 | 2016-01-23 01:42:20 |         NULL | NULL           |
+-----------+-------+-------------+---------------------+--------------+-------------------+
1 row in set (0.00 sec)

MariaDB [db_machine_learning]> select * from tbl_feature_count;
+---------+-----------+----------------+
| id_size | id_entity | count_features |
+---------+-----------+----------------+
|       1 |         1 |              7 |
+---------+-----------+----------------+
1 row in set (0.00 sec)

MariaDB [db_machine_learning]> select * from tbl_feature_value;
+----------+-----------+--------------------+----------------------+----------------------+
| id_value | id_entity | dep_variable_label | indep_variable_label | indep_variable_value |
+----------+-----------+--------------------+----------------------+----------------------+
|        1 |         1 | dep-variable-1     | indep-variable-6     |    0.002 |
|        2 |         1 | dep-variable-1     | indep-variable-7     |       25 |
|        3 |         1 | dep-variable-1     | indep-variable-4     |      325 |
|        4 |         1 | dep-variable-1     | indep-variable-5     |    54.64 |
|        5 |         1 | dep-variable-1     | indep-variable-2     |    98.01 |
|        6 |         1 | dep-variable-1     | indep-variable-3     |    0.432 |
|        7 |         1 | dep-variable-1     | indep-variable-1     |    23.45 |
|        8 |         1 | dep-variable-3     | indep-variable-6     |    0.002 |
|        9 |         1 | dep-variable-3     | indep-variable-7     |       24 |
|       10 |         1 | dep-variable-3     | indep-variable-4     |      427 |
|       11 |         1 | dep-variable-3     | indep-variable-5     |    75.45 |
|       12 |         1 | dep-variable-3     | indep-variable-2     |   101.21 |
|       13 |         1 | dep-variable-3     | indep-variable-3     |    0.832 |
|       14 |         1 | dep-variable-3     | indep-variable-1     |    22.67 |
|       15 |         1 | dep-variable-2     | indep-variable-6     |    0.001 |
|       16 |         1 | dep-variable-2     | indep-variable-7     |       31 |
|       17 |         1 | dep-variable-2     | indep-variable-4     |      235 |
|       18 |         1 | dep-variable-2     | indep-variable-5     |    64.45 |
|       19 |         1 | dep-variable-2     | indep-variable-2     |    92.22 |
|       20 |         1 | dep-variable-2     | indep-variable-3     |    0.356 |
|       21 |         1 | dep-variable-2     | indep-variable-1     |    24.32 |
+----------+-----------+--------------------+----------------------+----------------------+
21 rows in set (0.00 sec)

MariaDB [db_machine_learning]> show tables;
+-------------------------------+
| Tables_in_db_machine_learning |
+-------------------------------+
| tbl_dataset_entity            |
| tbl_feature_count             |
| tbl_feature_value             |
| tbl_observation_label         |
+-------------------------------+
4 rows in set (0.00 sec)

MariaDB [db_machine_learning]> select * from tbl_observation_label;
+----------+-----------+--------------------+
| id_label | id_entity | dep_variable_label |
+----------+-----------+--------------------+
|        1 |         1 | dep-variable-1     |
|        2 |         1 | dep-variable-3     |
|        3 |         1 | dep-variable-2     |
+----------+-----------+--------------------+
3 rows in set (0.00 sec)

MariaDB [db_machine_learning]>
```

However, a successive *data_append* was not able to append necessary data to the corresponding webform, generated by reactjs:

![data-append](https://cloud.githubusercontent.com/assets/2907085/12527837/a223e73a-c151-11e5-88c3-e5e4c69bd126.PNG)

**Comment by jeff1evesque** [comment]
Instead of an ajax [callback](https://github.com/jeff1evesque/machine-learning/blob/4724b413ac6cac367e2be6d784519df6abc967a1/src/jsx/import/data_append.jsx#L90-L102), that appends to DOM, we need to `return` corresponding session id, into reactjs states.  Then, we can generate reactjs components, respectively.

**Comment by jeff1evesque** [comment]
The committed `.bind(this)` implementation, generates the following error:

>Warning: validateDOMNesting(...): <span> cannot appear as a child of <select>. See SelectSession > DataAppend > select > span.

![dom-nesting](https://cloud.githubusercontent.com/assets/2907085/12533839/e2fc445c-c20d-11e5-8fad-48b0bd149fa0.PNG)

**Comment by jeff1evesque** [comment]
Since we are implementing asynchronous callbacks within our reactjs logic, with respect to an ajax process, we had to implement the callback within `data_append.jsx`:

![data-append](https://cloud.githubusercontent.com/assets/2907085/12542062/5f14821e-c2ec-11e5-97f4-bac1afe18ca2.PNG)

As we can see, this implementation correctly appends sessions id's to the `<select>` element, for `svm_session_id`.  This implementation, is the only one that will likely work.  Other solutions, are most likely variations of our implementation.

**Comment by jeff1evesque** [comment]
Our ajax asynchronous callbacks now properly return data from the server side, and stores them into reactjs states.  Now, we have to render these state values.

**Comment by jeff1evesque** [comment]
We got the ajax asynchronous callback, to properly append session attributes to as many `<option>` elements needed, under the `<select name="svm_session_id" ...>`:

![react-working](https://cloud.githubusercontent.com/assets/2907085/12572574/4a8e295a-c3bc-11e5-9bee-85ddce5b53af.PNG)

This means, we need to perform the following:

- implement submit button on the `data_append`, when the configuration elements have been defined
- recycle logic from `data_append`, to the `model_generate` case
- recycle logic from `data_append`, to the `model_predict` case

**Comment by jeff1evesque** [comment]
We have two remaining cases for this issue:

- implement necessary ajax logic within `model_predict` to ensure model is properly generated, and stored
- recycle logic from `data_append`, to the `model_predict` case

**Comment by jeff1evesque** [comment]
We need to implement the following:

```javascript
Object.entries(obj).forEach(function ([key, value]) { })
```

after we have installed the [object.entries](https://npmjs.com/object.entries) npm package.

**IRC #javascript (01/29/15 ~ 12:15am EST):**

>jeffreylevesque: you mean the npm package?
jeffreylevesque: there's no other javascript way?

>ljharb: jeffreylevesque: not yet. it's coming soon.

**Comment by jeff1evesque** [comment]
209b740,4aaca37: we found another javascript way, since `options` is originally a `string`, and needed to become an array via `JSON.parse()`.
