### ISSUE TITLE
'IndexError' within 'model_generate.py'

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/machine-learning#2473]
We need to resolve the following traceback, when creating a new model:

```bash
[2016-04-18 09:15:23,398] {/usr/local/lib/python2.7/dist-packages/flask/app.py:1423} ERROR - Exception on /load-data/ [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/interface/views.py", line 105, in load_data
    response = loader.load_model_generate()
  File "/vagrant/brain/load_data.py", line 141, in load_model_generate
    session.generate_model()
  File "/vagrant/brain/session/model_generate.py", line 86, in generate_model
    feature_count = feature_count['result'][0][0]
IndexError: tuple index out of range
```

**Note:** the above log was found within `/vagrant/log/access.log`, and may be a result of our attempt to provide kernel type choices (i.e. #1917) within `model_generate.jsx`.

**Comment by jeff1evesque** [comment]
Our problem is because, the feature count is not storing into the `tbl_feature_count` table:

```bash
MariaDB [(none)]> use db_machine_learning;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MariaDB [db_machine_learning]> show tables;
+-------------------------------+
| Tables_in_db_machine_learning |
+-------------------------------+
| tbl_dataset_entity            |
| tbl_feature_count             |
| tbl_feature_value             |
| tbl_observation_label         |
+-------------------------------+
4 rows in set (0.01 sec)

MariaDB [db_machine_learning]> select * from tbl_feature_count;
Empty set (0.00 sec)
```

**Comment by jeff1evesque** [comment]
The bug is a result of the following bad syntax within [`db_query.py`](https://github.com/jeff1evesque/machine-learning/blob/master/brain/database/db_query.py#L146-L149):

```python
                self.logger.log(
                    'transaction: success, statement' + sql_statement +
                    ', arguments: ' + arguments
                )
```
