### ISSUE TITLE
Create 'predict/svr.py' to generate svr model

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/machine-learning#2518]
We will create `predict/svr.py`, which will make predictions, using corresponding svr models.

**Note:** this issue is intended to supplement #2086, and should be resolved after #1922, since the redis structures are intended to support svr's, in addition to the current svm's.

**Comment by jeff1evesque** [comment]
We should also make a *note* within the docblock of `svr.py` (and `svm.py`), stating the following:

```python

```
@clf, an encoded model, which contains several builtin methods (i.e. `predict`)

**Comment by jeff1evesque** [comment]
We need to create a mechanism, within the `predict` method, from `model_predict.py`, to distinguish what type of operation will be performed (i.e. classification, regression).  Then we can adjust the following `return`:

```python
...
return svm_prediction('svm', self.model_id, self.predictors)
...
```

to the following:

```python
...
# devised solution
operation = get_operation(model_id)

# return prediction
return svm_prediction(operation, self.model_id, self.predictors)
...
```

This will allow us to reuse `brain/session/predict/svm.py`, which will require us to rename the corresponding file, and it's method, more generically (possibly `sv.py`, and `sv_prediction`).  If the latter is the case, then we'll need to adjust corresponding method references within `model_predict.py`, respectively.

**Comment by jeff1evesque** [comment]
4036c00: our committed `join` statement needs to be adjusted to the following pattern:

```mysql
FROM a JOIN b ON a.id = b.id JOIN c ON a.id2 = c.id
```

**Comment by jeff1evesque** [comment]
4036c00: our committed `join` statement needs to be adjusted to the following pattern:

```sql
FROM a JOIN b ON a.id = b.id JOIN c ON a.id2 = c.id
```

**Comment by jeff1evesque** [comment]
2a42906: we implement the `WHERE` clause for the following reason:

>static filtering is best done in the `WHERE` clause for readability (unless when using outer joins).

**Comment by jeff1evesque** [comment]
5ecb67f: we forgot to include the `WHERE` clause.

**Comment by jeff1evesque** [comment]
We are getting the following error during a *Data New* session:

>```bash
/vagrant/brain/database/db_query.py:119: Warning: Data truncated for column 'criterion' at row 1
  self.cursor.execute(sql_statement, sql_args)
```

**Comment by jeff1evesque** [comment]
We are getting the following error during a *Data New* session, when saving an svm dataset:

>```bash
/vagrant/brain/database/db_query.py:119: Warning: Data truncated for column 'criterion' at row 1
  self.cursor.execute(sql_statement, sql_args)
```

**Comment by jeff1evesque** [comment]
The `criterion` value, is stored via the `save_feature.py` script:

```bash
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ grep -r 'criterion' brain/database
brain/database/save_feature.py:                'criterion, indep_variable_label, indep_variable_value) '\
```

which is most likely instantiated via the `save_dataset.py` script:

```bash
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ grep -r 'save_feature' brain
brain/database/save_feature.py:'''@save_feature
brain/database/save_feature.py:    def save_feature(self, model_type):
brain/database/save_feature.py:        '''@save_feature
Binary file brain/database/save_feature.pyc matches
brain/load_data.py:                session.save_feature_count()
Binary file brain/load_data.pyc matches
brain/session/base_data.py:from brain.session.data.save_feature_count import feature_count
brain/session/base_data.py:    def save_feature_count(self):
brain/session/base_data.py:        '''@save_feature_count
Binary file brain/session/base_data.pyc matches
brain/session/data/save_dataset.py:from brain.database.save_feature import Save_Feature
brain/session/data/save_dataset.py:            db_return = db_save.save_feature(model_type)
Binary file brain/session/data/save_dataset.pyc matches
brain/session/data/save_feature_count.py:'''@save_feature_count
brain/session/data/save_feature_count.py:from brain.database.save_feature import Save_Feature
Binary file brain/session/data/save_feature_count.pyc matches
brain/session/data/validate_file_extension.py:'''@save_feature_count'''
Binary file brain/session/data/validate_file_extension.pyc matches
```

**Comment by jeff1evesque** [comment]
18b608e: we fixed the above error.  However, during *Model Predict* session (web-interface), we are not able to select an existing model, to perform a prediction, even though they exist:

```bash
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ redis-cli
127.0.0.1:6379> keys *
1) "svm_labels"
2) "svm_model"
3) "svm_feature_labels"
4) "svm_title"
127.0.0.1:6379> hgetall svm_model
1) "3_working_svm"
2) "ccopy_reg\n_reconstructor\np1\n(csklearn.svm.classes\nSVC\np2\nc__builtin__\nobject\np3\nNtRp4\n(dp5\nS'_impl'\np6\nS'c_svc'\np7\nsS'kernel'\np8\nS'linear'\np9\nsS'verbose'\np10\nI00\nsS'probability'\np11\nI00\nsS'classes_'\np12\ncnumpy.core.multiarray\n_reconstruct\np13\n(cnumpy\nndarray\np14\n(I0\ntS'b'\ntRp15\n(I1\n(I4\ntcnumpy\ndtype\np16\n(S'i8'\nI0\nI1\ntRp17\n(I3\nS'<'\nNNNI-1\nI-1\nI0\ntbI00\nS'\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x01\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x02\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x03\\x00\\x00\\x00\\x00\\x00\\x00\\x00'\ntbsS'support_'\np18\ng13\n(g14\n(I0\ntS'b'\ntRp19\n(I1\n(I5\ntg16\n(S'i4'\nI0\nI1\ntRp20\n(I3\nS'<'\nNNNI-1\nI-1\nI0\ntbI00\nS'\\x05\\x00\\x00\\x00\\x06\\x00\\x00\\x00\\x03\\x00\\x00\\x00\\x04\\x00\\x00\\x00\\x02\\x00\\x00\\x00'\ntbsS'dual_coef_'\np21\ng13\n(g14\n(I0\ntS'b'\ntRp22\n(I1\n(I3\nI5\ntg16\n(S'f8'\nI0\nI1\ntRp23\n(I3\nS'<'\nNNNI-1\nI-1\nI0\ntbI00\nS'i\\x93\\x82P!%(?i\\x93\\x82P!%(\\xbf\\xafR\\xf3\\x9d\\xe1to\\xbf\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x80\\xac\\xac\\x08\\x97q\\xc9m\\xbf\\xafR\\xf3\\x9d\\xe1to?:G\\xe2h0\\x152?\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x80:G\\xe2h0\\x152\\xbfpC\\x7f\\x80L\\xb8 \\xbf\\xac\\xac\\x08\\x97q\\xc9m?pC\\x7f\\x80L\\xb8 ?\\xb7Mkn\\xed\\x7fT?\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\xb7Mkn\\xed\\x7fT\\xbf'\ntbsS'shrinking'\np24\nI01\nsS'class_weight'\np25\nNsS'_gamma'\np26\nF0\nsS'probA_'\np27\ng13\n(g14\n(I0\ntS'b'\ntRp28\n(I1\n(I0\ntg23\nI00\nS''\ntbsS'_sparse'\np29\nI00\nsS'class_weight_'\np30\ng13\n(g14\n(I0\ntS'b'\ntRp31\n(I1\n(I4\ntg23\nI00\nS'\\x00\\x00\\x00\\x00\\x00\\x00\\xf0?\\x00\\x00\\x00\\x00\\x00\\x00\\xf0?\\x00\\x00\\x00\\x00\\x00\\x00\\xf0?\\x00\\x00\\x00\\x00\\x00\\x00\\xf0?'\ntbsS'random_state'\np32\nNsS'tol'\np33\nF0.001\nsS'coef0'\np34\nF0\nsS'nu'\np35\nF0\nsS'n_support_'\np36\ng13\n(g14\n(I0\ntS'b'\ntRp37\n(I1\n(I4\ntg20\nI00\nS'\\x01\\x00\\x00\\x00\\x01\\x00\\x00\\x00\\x02\\x00\\x00\\x00\\x01\\x00\\x00\\x00'\ntbsS'shape_fit_'\np38\n(I7\nI7\ntp39\nsS'C'\nF1\nsS'support_vectors_'\np40\ng13\n(g14\n(I0\ntS'b'\ntRp41\n(I1\n(I5\nI7\ntg23\nI00\nS'\\xfc\\xa9\\xf1\\xd2Mb`?\\x00\\x00\\x00\\x00\\x00\\x007@\\x00\\x00\\x00\\x00\\x00Pt@R\\xb8\\x1e\\x85\\xebQK@q=\\n\\xd7\\xa3\\x80X@\\xd9\\xce\\xf7S\\xe3\\xa5\\xdb?33333s7@\\xfc\\xa9\\xf1\\xd2Mb`?\\x00\\x00\\x00\\x00\\x00\\x00:@\\x00\\x00\\x00\\x00\\x00\\xb0z@\\xcd\\xcc\\xcc\\xcc\\xcc\\xdcR@=\\n\\xd7\\xa3pMY@9\\xb4\\xc8v\\xbe\\x9f\\xea?\\xecQ\\xb8\\x1e\\x85\\xab6@\\xfc\\xa9\\xf1\\xd2MbP?\\x00\\x00\\x00\\x00\\x00\\x00@@\\x00\\x00\\x00\\x00\\x00`u@{\\x14\\xaeG\\xe1\\xaaP@=\\n\\xd7\\xa3p\\xfdW@-\\xb2\\x9d\\xef\\xa7\\xc6\\xe7?\\x9a\\x99\\x99\\x99\\x99\\x196@\\xfc\\xa9\\xf1\\xd2MbP?\\x00\\x00\\x00\\x00\\x00\\x00>@\\x00\\x00\\x00\\x00\\x00`u@{\\x14\\xaeG\\xe1\\xeaR@\\x85\\xebQ\\xb8\\x1e\\xd5X@#\\xdb\\xf9~j\\xbc\\xe4?\\xf6(\\\\\\x8f\\xc2\\xb54@\\xfc\\xa9\\xf1\\xd2MbP?\\x00\\x00\\x00\\x00\\x00\\x00=@\\x00\\x00\\x00\\x00\\x00\\xf0r@q=\\n\\xd7\\xa3pM@R\\xb8\\x1e\\x85\\xebqX@\\xd1\"\\xdb\\xf9~j\\xe4?=\\n\\xd7\\xa3p\\xfd3@'\ntbsS'_dual_coef_'\np42\ng22\nsS'degree'\np43\nI3\nsS'epsilon'\np44\nF0\nsS'max_iter'\np45\nI-1\nsS'fit_status_'\np46\nI0\nsS'_intercept_'\np47\ng13\n(g14\n(I0\ntS'b'\ntRp48\n(I1\n(I6\ntg23\nI00\nS'\\xeaz$Go\\x88\\x1d@\\x00\\xd9\\xd9\\x10Q\\xa48@ `\\xe9I\\xd3\\x078\\xc0\\xd4;\\xa3Z\\x98\\x17\"\\xc0S\\xbb=O\\xb8\\xd2\\x17\\xc0+\\x88\\xa3\\xeedL0\\xc0'\ntbsS'intercept_'\np49\ng13\n(g14\n(I0\ntS'b'\ntRp50\n(I1\n(I6\ntg23\nI00\nS'\\xeaz$Go\\x88\\x1d@\\x00\\xd9\\xd9\\x10Q\\xa48@ `\\xe9I\\xd3\\x078\\xc0\\xd4;\\xa3Z\\x98\\x17\"\\xc0S\\xbb=O\\xb8\\xd2\\x17\\xc0+\\x88\\xa3\\xeedL0\\xc0'\ntbsS'probB_'\np51\ng13\n(g14\n(I0\ntS'b'\ntRp52\n(I1\n(I0\ntg23\nI00\nS''\ntbsS'cache_size'\np53\nI200\nsS'gamma'\np54\nF0\nsb."
```

**Comment by jeff1evesque** [comment]
We cleared the browser cache, then rebuilt our environment via `vagrant destroy`, followed by `vagrant up`.  Our SVM prediction was able to produce a corresponding prediction value.  However, the SVR case for the *Model Predict* session produced the following error, after submitting corresponding predictors:

```bash
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ python app.py
[2016-08-28 14:47:49,135] ERROR in app: Exception on /load-data/ [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/interface/views.py", line 127, in load_data
    response = loader.load_model_predict()
  File "/vagrant/brain/load_data.py", line 165, in load_model_predict
    my_prediction = session.predict()
  File "/vagrant/brain/session/model_predict.py", line 68, in predict
    return sv_prediction(model_type, self.model_id, self.predictors)
  File "/vagrant/brain/session/predict/sv.py", line 34, in sv_prediction
    model_id + '_' + title
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

**Comment by jeff1evesque** [comment]
When adding the following `print` statement within `brain/session/predict/sv.py`:

```bash
    # get necessary model
    title = Cache_Hset().uncache(
        model + '_title',
        model_id
    )['result']
    print model_id, title
```

submitting a corresponding *Model Predict* session yields the following within the corresponding `log/` file:

```bash
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ python app.py
2 None
[2016-08-28 14:52:33,879] ERROR in app: Exception on /load-data/ [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/interface/views.py", line 127, in load_data
    response = loader.load_model_predict()
  File "/vagrant/brain/load_data.py", line 165, in load_model_predict
    my_prediction = session.predict()
  File "/vagrant/brain/session/model_predict.py", line 68, in predict
    return sv_prediction(model_type, self.model_id, self.predictors)
  File "/vagrant/brain/session/predict/sv.py", line 35, in sv_prediction
    model_id + '_' + title
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

**Comment by jeff1evesque** [comment]
Our error, is because `retrieve_model_type.py` always returns the value `svm`.  Specifically, the following sql logic needs to be adjusted:

```python
...

        # select dataset
        self.sql.sql_connect(self.db_ml)
        sql_statement = 'SELECT mtype.model'\
            ' FROM tbl_dataset_entity mid'\
            ' INNER JOIN tbl_model_type mtype'\
            ' ON mid.model_type = mtype.id_model'\
            ' WHERE mid.id_entity=%s'
        args = (id_entity)
        response = self.sql.sql_command(sql_statement, 'select', args)

        # retrieve any error(s), disconnect from database
        response_error = self.sql.get_errors()
        self.sql.sql_disconnect()

        # return result
        if response_error:
            return {'error': response_error, 'result': None}
        else:
            return {'error': None, 'result': response['result'][0][0]}
...
```

**Comment by jeff1evesque** [comment]
The above statement has been verified.  We've adjust the `retrieve_model_type.py` to the following:

```python
...
        # select dataset
        self.sql.sql_connect(self.db_ml)
        sql_statement = 'SELECT mtype.model'\
            ' FROM tbl_dataset_entity mid'\
            ' INNER JOIN tbl_model_type mtype'\
            ' ON mid.model_type = mtype.id_model'\
            ' WHERE mid.id_entity=%s'
        args = (id_entity)
        response = self.sql.sql_command(sql_statement, 'select', args)

        # retrieve any error(s), disconnect from database
        response_error = self.sql.get_errors()
        self.sql.sql_disconnect()

        # return result
        if response_error:
            return {'error': response_error, 'result': None}
        else:
            print response['result'][0][0]
            return {'error': None, 'result': response['result'][0][0]}
...
```

Then, we loaded an svm dataset, followed by an svr dataset, both during a *Data New* session.  Next, we created corresponding sv models, during the *Model Generate* session.  Upon submitting a *Model Predict* for each of the generated models, we get the following traceback:

```bash
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ python app.py
svm
[2016-08-28 15:29:38,871] ERROR in app: Exception on /load-data/ [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/interface/views.py", line 127, in load_data
    response = loader.load_model_predict()
  File "/vagrant/brain/load_data.py", line 165, in load_model_predict
    my_prediction = session.predict()
  File "/vagrant/brain/session/model_predict.py", line 68, in predict
    return sv_prediction(model_type, self.model_id, self.predictors)
  File "/vagrant/brain/session/predict/sv.py", line 34, in sv_prediction
    model_id + '_' + title
TypeError: coercing to Unicode: need string or buffer, NoneType found
svm
```

**Note:** the latter traceback corresponds to the SVR prediction, while the former corresponds correctly to the SVM prediction.

**Comment by jeff1evesque** [comment]
The above sql errors are caused by improperly storing values into the `model_type` column of the `tbl_dataset_entity` table:

```sql
MariaDB [db_machine_learning]> select * from tbl_dataset_entity;
+-----------+-------+------------+-------------+---------------------+--------------+-------------------+
| id_entity | title | model_type | uid_created | datetime_created    | uid_modified | datetime_modified |
+-----------+-------+------------+-------------+---------------------+--------------+-------------------+
|         1 | svm   |          1 |           1 | 2016-08-28 18:44:44 |         NULL | NULL              |
|         2 | svr   |          1 |           1 | 2016-08-28 18:44:54 |         NULL | NULL              |
+-----------+-------+------------+-------------+---------------------+--------------+-------------------+
```

**Comment by jeff1evesque** [comment]
We completed and *Model Predict* using a generated SVR model. Upon submission, we received the following error traceback:

```bash
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ python app.py
[2016-08-28 22:15:33,401] ERROR in app: Exception on /load-data/ [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/interface/views.py", line 127, in load_data
    response = loader.load_model_predict()
  File "/vagrant/brain/load_data.py", line 165, in load_model_predict
    my_prediction = session.predict()
  File "/vagrant/brain/session/model_predict.py", line 68, in predict
    return sv_prediction(model_type, self.model_id, self.predictors)
  File "/vagrant/brain/session/predict/sv.py", line 45, in sv_prediction
    textual_label = list(encoded_labels.inverse_transform([numeric_label]))
  File "/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/label.py", line 168, in inverse_transform
    return self.classes_[y]
IndexError: arrays used as indices must be of integer (or boolean) type
```

**Note:** performing an SVM *Model Predict* simply yields a predicted value.

**Comment by jeff1evesque** [comment]
Our database structure is convoluted.  Specifically, the `tbl_feature_value` contains two columns, where the `dep_variable_label` column is used for SVM models, while the `criterion` column is used for SVR models:

```sql
MariaDB [db_machine_learning]> select * from tbl_feature_value;
+----------+-----------+--------------------+-----------+----------------------+----------------------+
| id_value | id_entity | dep_variable_label | criterion | indep_variable_label | indep_variable_value |
+----------+-----------+--------------------+-----------+----------------------+----------------------+
|        1 |         1 | dep-variable-5     |      NULL | indep-variable-6     |                0.001 |
|        2 |         1 | dep-variable-5     |      NULL | indep-variable-7     |                   27 |
|        3 |         1 | dep-variable-5     |      NULL | indep-variable-4     |                  295 |
|        4 |         1 | dep-variable-5     |      NULL | indep-variable-5     |                55.83 |
|        5 |         1 | dep-variable-5     |      NULL | indep-variable-2     |                95.03 |
|        6 |         1 | dep-variable-5     |      NULL | indep-variable-3     |                0.488 |
|        7 |         1 | dep-variable-5     |      NULL | indep-variable-1     |                23.27 |
|        8 |         1 | dep-variable-5     |      NULL | indep-variable-6     |                0.001 |
|        9 |         1 | dep-variable-5     |      NULL | indep-variable-7     |                   27 |
|       10 |         1 | dep-variable-5     |      NULL | indep-variable-4     |                  295 |
|       11 |         1 | dep-variable-5     |      NULL | indep-variable-5     |                55.83 |
|       12 |         1 | dep-variable-5     |      NULL | indep-variable-2     |                95.03 |
|       13 |         1 | dep-variable-5     |      NULL | indep-variable-3     |                0.488 |
|       14 |         1 | dep-variable-5     |      NULL | indep-variable-1     |                23.27 |
|       15 |         1 | dep-variable-5     |      NULL | indep-variable-6     |                0.001 |
|       16 |         1 | dep-variable-5     |      NULL | indep-variable-7     |                   29 |
|       17 |         1 | dep-variable-5     |      NULL | indep-variable-4     |                  303 |
|       18 |         1 | dep-variable-5     |      NULL | indep-variable-5     |                58.88 |
|       19 |         1 | dep-variable-5     |      NULL | indep-variable-2     |                97.78 |
|       20 |         1 | dep-variable-5     |      NULL | indep-variable-3     |                0.638 |
|       21 |         1 | dep-variable-5     |      NULL | indep-variable-1     |                19.99 |
|       22 |         1 | dep-variable-4     |      NULL | indep-variable-6     |                0.001 |
|       23 |         1 | dep-variable-4     |      NULL | indep-variable-7     |                   32 |
|       24 |         1 | dep-variable-4     |      NULL | indep-variable-4     |                  342 |
|       25 |         1 | dep-variable-4     |      NULL | indep-variable-5     |                66.67 |
|       26 |         1 | dep-variable-4     |      NULL | indep-variable-2     |                95.96 |
|       27 |         1 | dep-variable-4     |      NULL | indep-variable-3     |                0.743 |
|       28 |         1 | dep-variable-4     |      NULL | indep-variable-1     |                 22.1 |
|       29 |         1 | dep-variable-4     |      NULL | indep-variable-6     |                0.001 |
|       30 |         1 | dep-variable-4     |      NULL | indep-variable-7     |                   30 |
|       31 |         1 | dep-variable-4     |      NULL | indep-variable-4     |                  342 |
|       32 |         1 | dep-variable-4     |      NULL | indep-variable-5     |                75.67 |
|       33 |         1 | dep-variable-4     |      NULL | indep-variable-2     |                99.33 |
|       34 |         1 | dep-variable-4     |      NULL | indep-variable-3     |                0.648 |
|       35 |         1 | dep-variable-4     |      NULL | indep-variable-1     |                20.71 |
|       36 |         1 | dep-variable-1     |      NULL | indep-variable-6     |                0.002 |
|       37 |         1 | dep-variable-1     |      NULL | indep-variable-7     |                   23 |
|       38 |         1 | dep-variable-1     |      NULL | indep-variable-4     |                  325 |
|       39 |         1 | dep-variable-1     |      NULL | indep-variable-5     |                54.64 |
|       40 |         1 | dep-variable-1     |      NULL | indep-variable-2     |                98.01 |
|       41 |         1 | dep-variable-1     |      NULL | indep-variable-3     |                0.432 |
|       42 |         1 | dep-variable-1     |      NULL | indep-variable-1     |                23.45 |
|       43 |         1 | dep-variable-3     |      NULL | indep-variable-6     |                0.002 |
|       44 |         1 | dep-variable-3     |      NULL | indep-variable-7     |                   26 |
|       45 |         1 | dep-variable-3     |      NULL | indep-variable-4     |                  427 |
|       46 |         1 | dep-variable-3     |      NULL | indep-variable-5     |                75.45 |
|       47 |         1 | dep-variable-3     |      NULL | indep-variable-2     |               101.21 |
|       48 |         1 | dep-variable-3     |      NULL | indep-variable-3     |                0.832 |
|       49 |         1 | dep-variable-3     |      NULL | indep-variable-1     |                22.67 |
|       50 |         2 | dep-variable-5     |      NULL | indep-variable-6     |                0.001 |
|       51 |         2 | dep-variable-5     |      NULL | indep-variable-7     |                   27 |
|       52 |         2 | dep-variable-5     |      NULL | indep-variable-4     |                  295 |
|       53 |         2 | dep-variable-5     |      NULL | indep-variable-5     |                55.83 |
|       54 |         2 | dep-variable-5     |      NULL | indep-variable-2     |                95.03 |
|       55 |         2 | dep-variable-5     |      NULL | indep-variable-3     |                0.488 |
|       56 |         2 | dep-variable-5     |      NULL | indep-variable-1     |                23.27 |
|       57 |         2 | dep-variable-5     |      NULL | indep-variable-6     |                0.001 |
|       58 |         2 | dep-variable-5     |      NULL | indep-variable-7     |                   27 |
|       59 |         2 | dep-variable-5     |      NULL | indep-variable-4     |                  295 |
|       60 |         2 | dep-variable-5     |      NULL | indep-variable-5     |                55.83 |
|       61 |         2 | dep-variable-5     |      NULL | indep-variable-2     |                95.03 |
|       62 |         2 | dep-variable-5     |      NULL | indep-variable-3     |                0.488 |
|       63 |         2 | dep-variable-5     |      NULL | indep-variable-1     |                23.27 |
|       64 |         2 | dep-variable-5     |      NULL | indep-variable-6     |                0.001 |
|       65 |         2 | dep-variable-5     |      NULL | indep-variable-7     |                   29 |
|       66 |         2 | dep-variable-5     |      NULL | indep-variable-4     |                  303 |
|       67 |         2 | dep-variable-5     |      NULL | indep-variable-5     |                58.88 |
|       68 |         2 | dep-variable-5     |      NULL | indep-variable-2     |                97.78 |
|       69 |         2 | dep-variable-5     |      NULL | indep-variable-3     |                0.638 |
|       70 |         2 | dep-variable-5     |      NULL | indep-variable-1     |                19.99 |
|       71 |         2 | dep-variable-4     |      NULL | indep-variable-6     |                0.001 |
|       72 |         2 | dep-variable-4     |      NULL | indep-variable-7     |                   32 |
|       73 |         2 | dep-variable-4     |      NULL | indep-variable-4     |                  342 |
|       74 |         2 | dep-variable-4     |      NULL | indep-variable-5     |                66.67 |
|       75 |         2 | dep-variable-4     |      NULL | indep-variable-2     |                95.96 |
|       76 |         2 | dep-variable-4     |      NULL | indep-variable-3     |                0.743 |
|       77 |         2 | dep-variable-4     |      NULL | indep-variable-1     |                 22.1 |
|       78 |         2 | dep-variable-4     |      NULL | indep-variable-6     |                0.001 |
|       79 |         2 | dep-variable-4     |      NULL | indep-variable-7     |                   30 |
|       80 |         2 | dep-variable-4     |      NULL | indep-variable-4     |                  342 |
|       81 |         2 | dep-variable-4     |      NULL | indep-variable-5     |                75.67 |
|       82 |         2 | dep-variable-4     |      NULL | indep-variable-2     |                99.33 |
|       83 |         2 | dep-variable-4     |      NULL | indep-variable-3     |                0.648 |
|       84 |         2 | dep-variable-4     |      NULL | indep-variable-1     |                20.71 |
|       85 |         2 | dep-variable-1     |      NULL | indep-variable-6     |                0.002 |
|       86 |         2 | dep-variable-1     |      NULL | indep-variable-7     |                   23 |
|       87 |         2 | dep-variable-1     |      NULL | indep-variable-4     |                  325 |
|       88 |         2 | dep-variable-1     |      NULL | indep-variable-5     |                54.64 |
|       89 |         2 | dep-variable-1     |      NULL | indep-variable-2     |                98.01 |
|       90 |         2 | dep-variable-1     |      NULL | indep-variable-3     |                0.432 |
|       91 |         2 | dep-variable-1     |      NULL | indep-variable-1     |                23.45 |
|       92 |         2 | dep-variable-3     |      NULL | indep-variable-6     |                0.002 |
|       93 |         2 | dep-variable-3     |      NULL | indep-variable-7     |                   26 |
|       94 |         2 | dep-variable-3     |      NULL | indep-variable-4     |                  427 |
|       95 |         2 | dep-variable-3     |      NULL | indep-variable-5     |                75.45 |
|       96 |         2 | dep-variable-3     |      NULL | indep-variable-2     |               101.21 |
|       97 |         2 | dep-variable-3     |      NULL | indep-variable-3     |                0.832 |
|       98 |         2 | dep-variable-3     |      NULL | indep-variable-1     |                22.67 |
|       99 |         3 | NULL               |    54.666 | predictor-1          |                24.32 |
|      100 |         3 | NULL               |    54.666 | predictor-2          |                92.22 |
|      101 |         3 | NULL               |    54.666 | predictor-3          |                0.356 |
|      102 |         3 | NULL               |    54.666 | predictor-4          |                  235 |
|      103 |         3 | NULL               |    54.666 | predictor-5          |                64.45 |
|      104 |         3 | NULL               |    54.666 | predictor-6          |                0.001 |
|      105 |         3 | NULL               |    54.666 | predictor-7          |                   31 |
|      106 |         3 | NULL               |     22.02 | predictor-1          |                22.67 |
|      107 |         3 | NULL               |     22.02 | predictor-2          |               101.21 |
|      108 |         3 | NULL               |     22.02 | predictor-3          |                0.832 |
|      109 |         3 | NULL               |     22.02 | predictor-4          |                  427 |
|      110 |         3 | NULL               |     22.02 | predictor-5          |                75.45 |
|      111 |         3 | NULL               |     22.02 | predictor-6          |                0.002 |
|      112 |         3 | NULL               |     22.02 | predictor-7          |                   24 |
|      113 |         3 | NULL               |    34.543 | predictor-1          |                23.45 |
|      114 |         3 | NULL               |    34.543 | predictor-2          |                98.01 |
|      115 |         3 | NULL               |    34.543 | predictor-3          |                0.432 |
|      116 |         3 | NULL               |    34.543 | predictor-4          |                  325 |
|      117 |         3 | NULL               |    34.543 | predictor-5          |                54.64 |
|      118 |         3 | NULL               |    34.543 | predictor-6          |                0.002 |
|      119 |         3 | NULL               |    34.543 | predictor-7          |                   25 |
|      120 |         4 | NULL               |    54.666 | predictor-1          |                24.32 |
|      121 |         4 | NULL               |    54.666 | predictor-2          |                92.22 |
|      122 |         4 | NULL               |    54.666 | predictor-3          |                0.356 |
|      123 |         4 | NULL               |    54.666 | predictor-4          |                  235 |
|      124 |         4 | NULL               |    54.666 | predictor-5          |                64.45 |
|      125 |         4 | NULL               |    54.666 | predictor-6          |                0.001 |
|      126 |         4 | NULL               |    54.666 | predictor-7          |                   31 |
|      127 |         4 | NULL               |     22.02 | predictor-1          |                22.67 |
|      128 |         4 | NULL               |     22.02 | predictor-2          |               101.21 |
|      129 |         4 | NULL               |     22.02 | predictor-3          |                0.832 |
|      130 |         4 | NULL               |     22.02 | predictor-4          |                  427 |
|      131 |         4 | NULL               |     22.02 | predictor-5          |                75.45 |
|      132 |         4 | NULL               |     22.02 | predictor-6          |                0.002 |
|      133 |         4 | NULL               |     22.02 | predictor-7          |                   24 |
|      134 |         4 | NULL               |    34.543 | predictor-1          |                23.45 |
|      135 |         4 | NULL               |    34.543 | predictor-2          |                98.01 |
|      136 |         4 | NULL               |    34.543 | predictor-3          |                0.432 |
|      137 |         4 | NULL               |    34.543 | predictor-4          |                  325 |
|      138 |         4 | NULL               |    34.543 | predictor-5          |                54.64 |
|      139 |         4 | NULL               |    34.543 | predictor-6          |                0.002 |
|      140 |         4 | NULL               |    34.543 | predictor-7          |                   25 |
+----------+-----------+--------------------+-----------+----------------------+----------------------+
140 rows in set (0.00 sec)
```

This means, we need to adjust `brain/session/model/sv.py` to account for this discrepancy:
