### ISSUE TITLE
X.shape[0] should be equal to X.shape[1]

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/machine-learning#2562]
When implementing the `precomputed` kernel, during a *Model Generate*, we get the following error traceback within `flask.log`:

```bash
...
[2016-05-29 09:56:32,434] {/usr/local/lib/python2.7/dist-packages/flask/app.py:1587} ERROR - Exception on /load-data/ [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/interface/views.py", line 105, in load_data
    response = loader.load_model_generate()
  File "/vagrant/brain/load_data.py", line 141, in load_model_generate
    session.generate_model()
  File "/vagrant/brain/session/model_generate.py", line 62, in generate_model
    self.list_error
  File "/vagrant/brain/session/model/svm.py", line 90, in svm_model
    clf.fit(grouped_features, encoded_labels)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/svm/base.py", line 154, in fit
    raise ValueError("X.shape[0] should be equal to X.shape[1]")
ValueError: X.shape[0] should be equal to X.shape[1]
```

**Comment by jeff1evesque** [comment]
Both the [`SVC`](http://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html), and [`SVR`](http://scikit-learn.org/stable/modules/generated/sklearn.svm.SVR.htm) state the following:

>**Parameters:	**

>X : array-like, shape (n_samples, n_features)

>    For kernel=”precomputed”, the expected shape of X is [n_samples_test, n_samples_train].

**Comment by jeff1evesque** [comment]
We've decided to remove the `precomputed` kernel, since it requires multiple additional features:

- adjusted webform elements
  - adjusted webform UX flow
- additional backend logic to parse additional `POST` request in `views.py`
- adjusted backend prekernel step
  - necessary logic to 
- database adjustments, to store corresponding precomputed matrix
  - parser to ingest database
  - parser to extract from database
- puppet database build for corresponding table structure(s)

Therefore, we will either include the above features in a later milestone, or another flavor of this repository.  Additionally, the following documentation can provide greater insight regarding the `precomputed` kernel implementation:

- http://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html#sklearn.svm.SVC.fit

**Comment by jeff1evesque** [comment]
We've decided to remove the `precomputed` kernel, since it requires multiple additional features:

- adjusted webform elements
  - adjusted webform UX flow
- additional backend logic to parse additional `POST` request in `views.py`
- adjusted backend prekernel step
  - necessary logic between corresponding matrix to `fit` method
- database adjustments, to store corresponding precomputed matrix
  - parser to ingest database
  - parser to extract from database
- puppet database build for corresponding table structure(s)

Therefore, we will either include the above features in a later milestone, or another flavor of this repository.  Additionally, the following documentation can provide greater insight regarding the `precomputed` kernel implementation:

- http://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html#sklearn.svm.SVC.fit

For example, if either `clf = svm.SVC(kernel='precomputed')`, or `clf = svr.SVR(kernel='precomputed')`, then the following implementation requires `X` to be an `nxn` matrix:

```python
clf.fit(X, y)
clf.predict(X)
```
