### ISSUE TITLE
Implement 'pytest-flask' to streamline existing tests

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/machine-learning#2642]
Below was the original intention of this issue:

>This issue is a correction on #2641. Instead of directly focusing, and defining `conftest.py`, we will implement [flask-script](https://flask-script.readthedocs.io/en/latest/), to execute our unit testing.  Then, we may attempt to call our `py.test` implementation [from python](http://docs.pytest.org/en/latest/usage.html#calling-pytest-from-python-code) code.

However, as this issue matured, the following was the new target goal:

>We need to streamline our existing unit tests, such that a flask application is not a dependency to run unit tests.  Specifically, we need to be able to run our unit tests, without the precondition of having the corresponding python flask application, running beforehand.  We can investigate, and implement [pytest-flask](https://pytest-flask.readthedocs.io/en/latest), by using constructs like `live_server`, and `client.post()`.

**Comment by jeff1evesque** [comment]
A new `vagrant up` build, does not yield a functional application:

![localhost](https://cloud.githubusercontent.com/assets/2907085/16861812/4325e842-4a12-11e6-9dec-8098206cfb25.PNG)

Upon `vagrant ssh`, we notice the following error when manually starting `python app.py`:

```bash
vagrant@vagrant-ubuntu-trusty-64:~$ cd /vagrant
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ ls
app.py           factory.py   interface    puppet         src
brain            factory.pyc  license.md   README.md      test
build            hiera        log          run            Vagrantfile
contributing.md  hiera.yaml   manager.py   run_webserver
docker           __init__.py  manager.pyc  settings.pyc
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ python app.py
/usr/local/lib/python2.7/dist-packages/flask/exthook.py:71: ExtDeprecationWarnin
g: Importing flask.ext.script is deprecated, use flask_script instead.
  .format(x=modname), ExtDeprecationWarning
Traceback (most recent call last):
  File "app.py", line 16, in <module>
    from manager import Manager
  File "/vagrant/manager.py", line 17, in <module>
    class Manager(object):
  File "/vagrant/manager.py", line 38, in Manager
    @manager.command
NameError: name 'manager' is not defined
```

**Comment by jeff1evesque** [comment]
We need to determine if `current_app` exists within `factory.py` (if we `include` it), should the first `if` case is executed from a hypothetical `app.py`:

```bash
...
# implement app factory
if len(sys.argv) >= 2:
    # unit test
    if sys.argv[1] == 'test':
        app = create_app(sys.argv[1] + '/')
        manager = flask_manager(app, sys.argv[1] + '/')
    # other case
    elif sys.argv[1] == 'test2':
        app = create_app()
        manager = flask_manager(app, sys.argv[1] + '/')
    else:
        app.run(host='0.0.0.0')
else:
    app.run(host='0.0.0.0')
...
```

**Comment by jeff1evesque** [comment]
We decided to forgo the use of `flask-script`.  Instead, we hope to cleverly implement `pytest` on corresponding application factory instances, or `ctx` within the current `manager.py`.

**Note:** `manager.py` may be renamed, to better reflect the nature of the script.

**Comment by jeff1evesque** [comment]
We've been further debugging the `flask-script` [implementation](https://github.com/vitalk/pytest-flask/issues/45), and may return to this approach.

**Comment by jeff1evesque** [comment]
Additionally, the following two command differs, such that the second prints any trace which involve python `print` statements, while the first, will omit them:

```bash
$ python -m pytest
$ python -m pytest -s
```

**Comment by jeff1evesque** [comment]
The following implementation:

```python
'''@manager

This file implements the 'Manager' instance, which allows external scripts to
    be run within the corresponding flask script.  Specifically, 'pytest' is
    used to perform corresponding unit testing.

Note: the 'Manager', and 'pytest' instances can further be reviewed:

    - https://flask-script.readthedocs.io/en/latest/
    - http://docs.pytest.org/en/latest/usage.html

'''

import urllib2
from flask import Flask, url_for
import pytest


import requests
import json
import os.path

def test_add_endpoint_to_live_server(accept_json, client, live_server):
    @live_server.app.route('/load-data/')
    def get_endpoint():
        return url_for('name.load_data', _external=True)

    live_server.start()

    assert client.post(
        get_endpoint(),
        headers={'Content-Type': 'application/json'},
        data=get_sample_json('svm-data-new.json', 'svm')
    )

def get_sample_json(jsonfile, model_type):
    '''@get_sample_json

    Get a sample json dataset.

    '''

    json_dataset = None
    with open(
        '/vagrant/' + os.path.join(
            'interface',
            'static',
            'data',
            'json',
            'programmatic_interface',
            model_type,
            jsonfile
        ),
        'r'
    ) as json_file:
        json_dataset = json.load(json_file)
    return json.dumps(json_dataset)
```

Should be equivalent to manually running the `check_data_new` [implementation](https://github.com/jeff1evesque/machine-learning/blob/master/test/programmatic_interface/pytest_svm_session.py#L37-L733) within `pytest_svm_session.py`.

**Comment by jeff1evesque** [comment]
The following syntax is more polished of the above working example:

```python
# @manager

import urllib2
from flask import Flask, url_for
import pytest
import json
import os.path

def test_add_endpoint_to_live_server(accept_json, client, live_server):
    @live_server.app.route('/load-data/')
    def get_endpoint():
        return url_for('name.load_data', _external=True)

    live_server.start()

    res = client.post(
        get_endpoint(),
        headers={'Content-Type': 'application/json'},
        data=get_sample_json('svm-data-new.json', 'svm')
    )
    assert res.status_code == 200

def get_sample_json(jsonfile, model_type):
    '''@get_sample_json

    Get a sample json dataset.

    '''

    json_dataset = None
    with open(
        '/vagrant/' + os.path.join(
            'interface',
            'static',
            'data',
            'json',
            'programmatic_interface',
            model_type,
            jsonfile
        ),
        'r'
    ) as json_file:
        json_dataset = json.load(json_file)
    return json.dumps(json_dataset)
```

Additionally, we've checked the above test, does in fact add corresponding items to the sql database.

**Comment by jeff1evesque** [comment]
Since, we've successfully prototyped pytest-flask, we have [decided](https://github.com/jeff1evesque/machine-learning/issues/2645) to install the pytest-flask package.

**Comment by jeff1evesque** [comment]
If we adjust our current [`test/hiera/settings.yaml`}(https://github.com/jeff1evesque/machine-learning/blob/56416c24ce21c5c340cbbc384b3ca6db170a3feb/test/hiera/settings.yaml), to the following:

```yaml
...
## variables
general:
    environment: 'docker'
    vagrant_implement: false
    root: '/vagrant'
    host: 'localhost'
    user: 'root'
    group: 'root'
...
```

Then, within our vagrant environment, we `kill` any processes associated with our flask `app.py` (anything attached to the default port `5000`):

```bash
vagrant@vagrant-ubuntu-trusty-64:~$ cd /vagrant
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ netstat -ntlup
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
PID/Program name
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN
-
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
-
tcp        0      0 0.0.0.0:33572           0.0.0.0:*               LISTEN
-
tcp        0      0 0.0.0.0:5000            0.0.0.0:*               LISTEN
12724/python
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN
-
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN
-
tcp6       0      0 :::111                  :::*                    LISTEN
-
tcp6       0      0 :::22                   :::*                    LISTEN
-
tcp6       0      0 :::49151                :::*                    LISTEN
-
udp        0      0 0.0.0.0:111             0.0.0.0:*
-
udp        0      0 0.0.0.0:18836           0.0.0.0:*
-
udp        0      0 0.0.0.0:38083           0.0.0.0:*
-
udp        0      0 0.0.0.0:720             0.0.0.0:*
-
udp        0      0 127.0.0.1:754           0.0.0.0:*
-
udp        0      0 0.0.0.0:68              0.0.0.0:*
-
udp6       0      0 :::111                  :::*
-
udp6       0      0 :::720                  :::*
-
udp6       0      0 :::57337                :::*
-
udp6       0      0 :::7483                 :::*
-
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ kill 12724
```

We can verify that our pytest-flask unit testing works as expected:

```bash
vagrant@vagrant-ubuntu-trusty-64:/vagrant/test$ python -m pytest -s
============================= test session starts ==============================

platform linux2 -- Python 2.7.6, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: /vagrant/test, inifile: pytest.ini
plugins: flask-0.10.0
collected 6 items

programmatic_interface/pytest_svm_session.py ....
programmatic_interface/pytest_svr_session.py ..

========================== 6 passed in 15.41 seconds ===========================
```
