### ISSUE TITLE
Create application tray for main sessions

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/machine-learning#2727]
We will create a vertical navigation bar, which will be responsible for updating the main content area.  This navigation bar will be fixed with the following four session types:
- data new: upload new dataset(s)
- data append: upload additional dataset(s) to previous upload
- model generate: generate a desired model
- model predict: perform a prediction from previous model

The application tray for our main sessions will be contained under the _navbar_ section:

![layout](https://cloud.githubusercontent.com/assets/2907085/18608991/21720cae-7cc5-11e6-9dc1-f1c78f5a7fb4.png)

This section will be much larger than shown, when designed for the webpage.  Therefore, it will give us flexibility (with time), to decide how to stylistically create the inner layout.  However, the navbar will collapse above the _main page_, while the _user menu_ will collapse to a toggle button (if that wasn't already the case) above the _navbar_.

**Comment by jeff1evesque** [comment]
The following pattern should work:

```javascript
/**
 * navbar.jsx: secondary menu..
 *
 * Note: this script implements jsx (reactjs) syntax.
 */

import React from 'react'
import { render } from 'react-dom'
import { Router, Route, Link, browserHistory } from 'react-router'

var NavBar = React.createClass({
  // display result
    render: function() {
        return(
            <Link to={`/user`}><div className='main-sidebar'>jeff</div></Link>
        );
    }
});

// indicate which class can be exported, and instantiated via 'require'
export default NavBar
```

However, we still need to set up the router definition, in another file.  Then, we can `import` it in the entry point, and render it in a `<Router>` element.

**Comment by jeff1evesque** [comment]
Our `browserify.log` is generating the following error:

```bash
[2016-11-01 19:38:21] browserify service watcher starting
[2016-11-01:19:38:21] + cat /dev/null
[2016-11-01:19:38:21] + cd /usr/lib/node_modules
[2016-11-01:19:38:21] + browserify /vagrant/src/jsx/content.jsx -t '[' babelify --presets es2015,react ']' -o /vagrant/src/js/content.js
[2016-11-01:19:38:21] + inotifywait /vagrant/src/jsx/ -m -r -e close_write -e move
[2016-11-01:19:38:21] Setting up watches.  Beware: since -r was given, this may take a while!
[2016-11-01:19:38:27] Watches established.
[2016-11-01:19:38:28] Error: Cannot find module 'react-router' from '/vagrant/src/jsx/import/navigation'
[2016-11-01:19:38:28] at /usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
[2016-11-01:19:38:28] at process (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
[2016-11-01:19:38:28] at ondir (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
[2016-11-01:19:38:28] at load (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
[2016-11-01:19:38:28] at onex (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
[2016-11-01:19:38:28] at /usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
[2016-11-01:19:38:28] at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by jeff1evesque** [comment]
Though #2789 was successfully installed globally, it is not supposed to be installed globally.

**Comment by jeff1evesque** [comment]
Though, we have the following `deprecation` warning:

>content.min.js:2 Warning: You are manually calling a React.PropTypes validation function for the `to` prop on `Link`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

We made progress by having the `<Link>` to render text within the browser:

![deprecated-link](https://cloud.githubusercontent.com/assets/2907085/19913739/b44a2b2c-a07b-11e6-970e-21785e8a5c66.PNG)

**Comment by jeff1evesque** [comment]
The above commits fixes the [above](https://github.com/jeff1evesque/machine-learning/issues/2727#issuecomment-257749354) `deprecation` notices:

![fixed](https://cloud.githubusercontent.com/assets/2907085/19916424/5339c4fe-a090-11e6-8779-d312592965c4.PNG)

**Comment by jeff1evesque** [comment]
We still need to style the application tray, as well as define, and implement the `react-router`s.

**Comment by jeff1evesque** [comment]
We need to implement the `router` definitions, so we can further style the side menu:

![adjusted-menu](https://cloud.githubusercontent.com/assets/2907085/19927328/a8ad1ab4-a0cf-11e6-9f2b-e3cda84ed5d1.PNG)

**Comment by jeff1evesque** [comment]
We need to adjust `content.jsx` to implement router syntax:

```javascript
/**
 * content.jsx: generate main content.
 *
 * Note: this script implements jsx (reactjs) syntax.
 */

import React from 'react';
import ReactDOM from 'react-dom';
import SupportVector from './import/content/support_vector.jsx';
import LoginForm from './import/content/login.jsx';
import RegisterForm from './import/content/register.jsx';
import NavBar from './import/navigation/nav_bar.jsx';
import UserMenu from './import/navigation/user_menu.jsx';

var Content = React.createClass({
  // initial 'state properties'
    getInitialState: function() {
        return {
            render_login: false,
            render_registration: false,
        };
    },
  // update 'state properties': click event has not 'target'
    setClickType: function(event){
        if (event.home) {
            this.setState({render_login: false});
            this.setState({render_registration: false});
            this.setState({render_home: true});
        }
        else if (event.login) {
            this.setState({render_home: false});
            this.setState({render_registration: false});
            this.setState({render_login: true});
        }
        else if (event.register) {
            this.setState({render_home: false});
            this.setState({render_login: false});
            this.setState({render_registration: true});
        }
    },
  // display result
    render: function() {
        var SideBar = this.getNavBar();
        return(
            <div className='container-inner'>
                <div className='menu-container'>
                    <UserMenu onChange={this.setClickType} />
                </div>
                <div className='main'>
                    <SideBar />
                    {this.props.children}
                </div>
            </div>
        );
    }
});

const MainLayout = (props) => (
    <div>
        <NavBar />
        {props.children}
    </div>
);

// render form
ReactDOM.render(
    <Router>
        <Route path="/" component={Content}>
            <Route component={Login} path="/login" />
            <Route component={MainLayout}>
                <Route component={Whatever} path="/whatever" />
            </Route>
        </Route>
    </Router>,
    document.querySelector('.container')
);
```
Though, the above code may need further adjustments, we should eventually remove the `setClickType` implementation, and instead, use react-router's `Link`.

**Comment by jeff1evesque** [comment]
We needed to implement the [`history`](https://github.com/ReactTraining/react-router/blob/master/docs/guides/Histories.md) syntax:

```javascript
// JavaScript module import
import { browserHistory } from 'react-router'
...
            <Router history={browserHistory}>
                <Route path='/' component={this.props.indexRoute} >
                    <Route path='/data-new' component={DataNew} />
                    <Route path='/data-append' component={DataAppend} />
                    <Route path='/model-generate' component={ModelGenerate} />
                    <Route path='/model-predict' component={ModelPredict} />
                </Route>
            </Router>
...
```

Otherwise, we would experience the following error within the browser console:

```bash
content.min.js:5 Uncaught TypeError: Cannot read property 'getCurrentLocation' of 
undefined(…)createTransitionManager @ content.min.js:5Router_componentWillMount @ 
content.min.js:5(anonymous function) @ content.min.js:10measureLifeCyclePerf @ 
content.min.js:9performInitialMount @ content.min.js:10mountComponent @ 
content.min.js:9mountComponent @ content.min.js:14performInitialMount @ 
content.min.js:10mountComponent @ content.min.js:9mountComponent @ 
content.min.js:14performInitialMount @ content.min.js:10mountComponent @ 
content.min.js:9mountComponent @ content.min.js:14mountComponentIntoNode @ 
content.min.js:13perform @ content.min.js:16batchedMountComponentIntoNode @ 
content.min.js:13perform @ content.min.js:16batchedUpdates @ content.min.js:12batchedUpdates @ 
content.min.js:15_renderNewRootComponent @ content.min.js:13_renderSubtreeIntoContainer @ 
content.min.js:14render @ content.min.js:14r.2../import/content/login.jsx @ content.min.js:1s @ 
content.min.js:1e @ content.min.js:1(anonymous function) @ content.min.js:1
```

**Comment by jeff1evesque** [comment]
We need to determine if we can implement `<Content routerProp={this.props.children}/>` from `content.jsx`, and access the corresponding `this.prop.routerProp` from `SupportVector.jsx`.  Hopefully, we can dynamically render components, rather than having to directly render `{this.props.children}` within `content.jsx`, at the potential expense of having to restructure the entire jsx implementation.

**Comment by jeff1evesque** [comment]
When one of the navigation menu items is clicked (i.e. sidebar), the successive *Data Upload* component is rendered correctly:

![working-propagation](https://cloud.githubusercontent.com/assets/2907085/19995466/da655a08-a22d-11e6-8d09-848632f766ef.PNG)

However, the `<select>` element from the *Session Type* fieldset is not updated. This error corresponds to the `console.log` traceback error:

>content.min.js:3 Warning: `value` prop on `input` should not be null. Consider using the empty string to clear the component or `undefined` for uncontrolled components.
    in input (created by DataNew)
    in fieldset (created by DataNew)
    in fieldset (created by DataNew)
    in DataNew (created by SupportVector)
    in form (created by SupportVector)
    in div (created by SupportVector)
    in SupportVector (created by MainLayout)
    in div (created by MainLayout)
    in MainLayout (created by RouterContext)
    in div (created by Page)
    in div (created by Page)
    in Page (created by RouterContext)
    in RouterContext (created by Router)
    in Router (created by AppRouter)
    in AppRouter

The above error cannot be fixed within the same section of `support_vector.jsx`, since it would lead to infinite recursion, between the two components, within the browser:

```javascript
...
    render: function() {
        var Result = ResultDisplay;
        var routerProp = this.props.routerProp;

      // render from router
        if (routerProp) {
          // debug
          //  console.log(routerProp);

          // local variables
            var SessionType = routerProp.props.route.component;
        }
...
```

**Comment by jeff1evesque** [comment]
Only the `data_new`, and `data_append` session properly adjust the wrapping html parent:

![data_new](https://cloud.githubusercontent.com/assets/2907085/20038487/cea2884a-a402-11e6-9298-a5b373a9050c.PNG)

![data_append](https://cloud.githubusercontent.com/assets/2907085/20038489/d2d9d210-a402-11e6-8f74-d1459221cdbb.PNG)

But, after implementing both (above) sessions, the `model_generate`, and `model_predict` session are not responsive:

![model-generate](https://cloud.githubusercontent.com/assets/2907085/20038522/2893a776-a403-11e6-87f2-971afbc04158.PNG)

![model-predict](https://cloud.githubusercontent.com/assets/2907085/20038524/2d642c8a-a403-11e6-9ecb-f71e2d31d5a7.PNG)

However, if they are accessed directly (before `data_new`, or `data_append`):

![model-generate-2](https://cloud.githubusercontent.com/assets/2907085/20038527/3cef74c0-a403-11e6-936e-c7417ce1a848.PNG)

![model-predict-2](https://cloud.githubusercontent.com/assets/2907085/20038530/4163b82c-a403-11e6-8832-7fdbb6750726.PNG)

**Comment by jeff1evesque** [comment]
We need to store`routerProp.props.route.component` into a state variable, and check if future instances are equal. This means we can adjust the following conditions:

**Comment by jeff1evesque** [comment]
Any sidebar menu link choices, results in the browser console to output:

>content.min.js:1 Uncaught TypeError: Cannot read property 'route' of undefined(…)

**Comment by jeff1evesque** [comment]
The current commits produces a working intended code, with the exception that the registration, and login pages do not properly load in the browser.

**Comment by jeff1evesque** [comment]
We need to create a trivial `main.jsx`, which returns a single empty `<div className='main-inner'>` wrapper.  This will allow us to change the current router implementation:

```javascript
...
            <Router history={browserHistory}>
                <Route component={this.props.indexRoute}>
                    <Route path='/' component={AnalysisLayout}>
                        <Route
                            path='/session/data-new'
                            component={DataNew}
                        />
                        <Route
                            path='/session/data-append'
                            component={DataAppend}
                        />
                        <Route
                            path='/session/model-generate'
                            component={ModelGenerate}
                        />
                        <Route
                            path='/session/model-predict'
                            component={ModelPredict}
                        />
                    </Route>
                </Route>
            </Router>
...
```

to something of the following form:

```bash
...
            <Router history={browserHistory}>
                <Route component={this.props.indexRoute}>
                    <Route path='/' component={Main}>
                        <Route path='/session' component={AnalysisLayout}>
                            <Route
                                path='/session/data-new'
                                component={DataNew}
                            />
                            <Route
                                path='/session/data-append'
                                component={DataAppend}
                            />
                            <Route
                                path='/session/model-generate'
                                component={ModelGenerate}
                            />
                            <Route
                                path='/session/model-predict'
                                component={ModelPredict}
                            />
                        </Route>
                    </Route>
                </Route>
            </Router>
...
```

**Comment by jeff1evesque** [comment]
We've fixed our user menu, and it functions as intended.  However, the sidebar no longer works as [earlier stated](https://github.com/jeff1evesque/machine-learning/issues/2727#issuecomment-259012033).
