### ISSUE TITLE
Implement gunicorn as a precursor to #2830

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/machine-learning#2832]
We are currently receiving a 502 Bad Gateway error from #2830. Specifically, nginx is unable to forward incoming requests to our flask + gunicorn application, since gunicorn doesn't seem to be properly running.  So, we will dedicate this issue as a precursor, to partially debug #2830, by ensuring gunicorn is trivially running, with respect to our app factory implementation.

**Comment by jeff1evesque** [comment]
We removed the generated `/etc/init/start_gunicorn.conf`, then restarted the vagrant vm:

```bash
vagrant halt
vagrant up
```

Then, we proceeded to halt the corresponding nginx process:

```bash
vagrant@vagrant-ubuntu-trusty-64:~$ sudo service nginx stop
vagrant@vagrant-ubuntu-trusty-64:~$ sudo service nginx status
 * nginx is not running
```

However, it seems the traditional flask application we've previous run, no longer works:

```bash
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ python app.py
Traceback (most recent call last):
  File "app.py", line 31, in <module>
    app = create_app()
  File "/vagrant/factory.py", line 112, in create_app
    logger = Logger('error', 'yaml')
  File "/vagrant/log/logger.py", line 56, in __init__
    level = current_app.config.get('LOG_LEVEL')
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 302, in _get_current_object
    return self.__local()
  File "/usr/local/lib/python2.7/dist-packages/flask/globals.py", line 51, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in a way.  To solve
this set up an application context with app.app_context().  See the
documentation for more information.
```

We need to investigate how the committed code changes the traditional flask application.

**Comment by jeff1evesque** [comment]
Even after removing the `nginx` package:

```bash
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ sudo apt-get remove nginx
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  acl at-spi2-core augeas-lenses colord dconf-gsettings-backend dconf-service
  libasound2 libasound2-data libatk-bridge2.0-0 libatspi2.0-0 libaugeas0
  libcairo-gobject2 libcanberra-gtk3-0 libcanberra-gtk3-module libcanberra0
  libcolord1 libcolorhug1 libdconf1 libdrm-intel1 libdrm-nouveau2
  libdrm-radeon1 libexif12 libfontenc1 libgd3 libgl1-mesa-dri libgl1-mesa-glx
  libglapi-mesa libgphoto2-6 libgphoto2-l10n libgphoto2-port10 libgtk-3-0
  libgtk-3-bin libgtk-3-common libgudev-1.0-0 libgusb2 libice6 libieee1284-3
  libllvm3.4 libltdl7 libnotify-bin libnotify4 libogg0 libpciaccess0 libsane
  libsane-common libsm6 libtdb1 libtxc-dxtn-s2tc0 libv4l-0 libv4lconvert0
  libvorbis0a libvorbisfile3 libvpx1 libwayland-client0 libwayland-cursor0
  libx11-xcb1 libxaw7 libxcb-dri2-0 libxcb-dri3-0 libxcb-glx0 libxcb-present0
  libxcb-sync1 libxfont1 libxkbcommon0 libxkbfile1 libxmu6 libxpm4
  libxshmfence1 libxt6 libxtst6 libxxf86vm1 notification-daemon ruby-augeas
  ruby-hiera ruby-rgen ruby-safe-yaml ruby-shadow sound-theme-freedesktop
  x11-xkb-utils xfonts-base xfonts-encodings xfonts-utils xserver-common
  xserver-xorg-core
Use 'apt-get autoremove' to remove them.
The following packages will be REMOVED:
  nginx
0 upgraded, 0 newly installed, 1 to remove and 69 not upgraded.
After this operation, 2,465 kB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 78587 files and directories currently installed.)
Removing nginx (1.10.2-1~trusty) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
```

The earlier traceback error still persists, when attempting to run the flask application, as traditional done on the current `master` branch:

```bash
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ python app.py
Traceback (most recent call last):
  File "app.py", line 31, in <module>
    app = create_app()
  File "/vagrant/factory.py", line 112, in create_app
    logger = Logger('error', 'yaml')
  File "/vagrant/log/logger.py", line 56, in __init__
    level = current_app.config.get('LOG_LEVEL')
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 302, in _get_current_object
    return self.__local()
  File "/usr/local/lib/python2.7/dist-packages/flask/globals.py", line 51, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in a way.  To solve
this set up an application context with app.app_context().  See the
documentation for more information.
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ sudo python app.py
Traceback (most recent call last):
  File "app.py", line 31, in <module>
    app = create_app()
  File "/vagrant/factory.py", line 112, in create_app
    logger = Logger('error', 'yaml')
  File "/vagrant/log/logger.py", line 56, in __init__
    level = current_app.config.get('LOG_LEVEL')
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 302, in _get_current_object
    return self.__local()
  File "/usr/local/lib/python2.7/dist-packages/flask/globals.py", line 51, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in a way.  To solve
this set up an application context with app.app_context().  See the
documentation for more information.
```

**Comment by jeff1evesque** [comment]
For completeness, we checked if the current `master` branch is working as intended.  So, we proceeded by destroying the current build, based on `feature-2832`, and rebuilding `(git checkout master && vagrant up)`.  We noticed the application is performing as expected.

**Comment by jeff1evesque** [comment]
We temporarily commented out the following segment from `puppet/environment/vagrant/modules/webserver/manifests/start.pp`, and rebuilt a new vagrant instance:

```puppet
### Note: the prefix 'vagrant::', corresponds to a puppet convention:
###
###       https://github.com/jeff1evesque/machine-learning/issues/2349
###
class webserver::start {
    # variables
    $hiera_general   = hiera('general')
    $vagrant_mounted = $hiera_general['vagrant_implement']

#    # run gunicorn
#    if $vagrant_mounted {
#        # ensure service starts at boot
#        service { 'start_gunicorn':
#            ensure => 'running',
#            enable => true,
#        }
#    }
#    else {
#        # run and restart when needed
#        service { 'start_gunicorn':
#            ensure => 'running',
#        }
#    }
}
```

However, we still received the same traceback error as above.

**Comment by jeff1evesque** [comment]
In addition to commenting out the above `start.pp`, we temporarily commented out the following snippet from `puppet/environment/vagrant/modules/webserver/manifests/service.pp`:

```puppet
...
#    ## dos2unix: convert clrf (windows to linux) in case host machine is
#    #            windows.
#    file { '/etc/init/start_gunicorn.conf':
#        ensure  => file,
#        content => dos2unix(template($template_path)),
#    }
...
```
