### ISSUE TITLE
Replace flask default session cookie with redis

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/machine-learning#2868]
We need to replace the current flask session cookie, with an implementation of redis, or similar.  The motivation for this enhancement, is greater security, and better performance.  However, if we decide to implement redis, we may choose from the following options:

Option 1:
---------

Ensure the following lines exists within [`factory.py`](https://github.com/jeff1evesque/machine-learning/blob/1f5d8cbddc1925a0fbd3ec5d2ae1fc8db5e4506c/factory.py#L52):

```python
from brain.cache.redis_session import RedisSessionInterface
...
    # replace default cookie session with server-side redis
    app.session_interface = RedisSessionInterface()

    # secret key: used for maintaining flask sessions
    app.secret_key = settings['application']['security_key']
```

Followed by making necessary adjustments to [`redis_session.py`](https://github.com/jeff1evesque/machine-learning/blob/65b1baa4e0784a4eb208fd404b2e24e667128d4f/brain/cache/redis_session.py), as well as the overall docker implementation employed by our [`travis.yml`](https://github.com/jeff1evesque/machine-learning/blob/5e424f82e91b7cf03a939cecba1674ce5445989a/.travis.yml#L103-L114)

**Option 2:**
--------------

Implement [flask-session](https://pythonhosted.org/Flask-Session/), then remove the existing [`redis_session.py`](https://github.com/jeff1evesque/machine-learning/blob/65b1baa4e0784a4eb208fd404b2e24e667128d4f/brain/cache/redis_session.py).

**Note:** this issue is an extension of an earlier attempted #2863.

**Comment by jeff1evesque** [comment]
Adding references of issues, and comments in case a refresher is needed in the future:

- https://github.com/pallets/flask/issues/2150#issuecomment-272599771
- https://github.com/jeff1evesque/machine-learning/pull/2867#issuecomment-272431783
- https://github.com/jeff1evesque/machine-learning/pull/2867#issuecomment-272650814

**Comment by jeff1evesque** [comment]
Some additional information has been provided, via the flask email group:

- https://mail.python.org/pipermail/flask/2017-January/000711.html

**Comment by jeff1evesque** [comment]
We will be renaming `redis_session.py` to `session.py` via #2816.

**Comment by jeff1evesque** [comment]
We may take a closer look at the following for additional examples, of how to implement flask-session:

- https://stackoverflow.com/a/45393532

**Comment by jeff1evesque** [comment]
If our attempt of option 1 succeeds, then we'll need to move the following absolute definition:

```python
    def __init__(self, prefix='session:'):
        # local variables
        host = 'localhost'
        port = 6379
        db_num = 0
```

To be more dynamic, using flask session variables. This means, we'll need to move the corresponding parameter values, into a corresponding yaml configuration.

**Comment by jeff1evesque** [comment]
After the above commits, we `vagrant destroy -f` (twice), followed up by `vagrant up`. Then, we successfully, `/register` a new `jeff1evesque` user:

```sql
MariaDB [db_machine_learning]> select * from tbl_user;
+---------+--------------+------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| id_user | username     | email                  | password                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | datetime_joined     |
+---------+--------------+------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
|       1 | jeff1evesque | jeff1evesque@yahoo.com | 6ec8djk234h2343;q34280d4db84a9c7f8a6afdeb872ba0006b69eaa25dcde4a1d98cb6e6ebe17aa7159c492ae9df29df81e2094f2b6df0c5837a5a44d046f17794105fdd96bfaf6ad098423217ed5dc3b2b0a0cda087152d99ab0a93db087785b9cc3615b1fe1932af209857459c3304a085c91ecd3b0cc8b57993a513da9e0de91c73c2409f919b60ce42a99c7144900332e536b2aa5374908a62a9f8877fe66f5bb4f8d84b419bb460f16f847e616e3a9ffbfabdc1f05515118e20c092a623d1eeaf33222b93660e67eb6kldsaf089dasf7ajk30f5c14b5f18255a909822e3c8324c265f8efd92242beb0c443491f860a71e2f7d95a8d3d8cdebe16cf10e1b8dba861318d8abe05a0feea9ccd93820fcb43756d5f14a4fa5168de04b5ae3fcfd9a0ff58067e3b4f3695d5772c7a616972b5820c3a3f5b42647c660eb703077404f114a2b0a69213f6117d5cb69b3dc32d989bc25a78863e3abf86682bbe433976a4b5f75565aaf592a54c140b67aa6afb7a69608a2ebabd0f4aabda2fa10aa5c8d117ebd1897cab612448163761dc7ab0dfe4eb8bcb4a68af4c858eae7c0f0d6b8de571303d82b59cc0824607040f7828b5c713e5cb531b228c15de572654ca7c88a7aac1173356e206b9fb5ed8cdb707b8ecb201bcc8a0d27ee6ec2254d7b2c3a821258cd2bd66be0$Hj4JoLkKz44s3fomF9AVZy7ifmQKezN0T2pz1XW2CoY= | 2017-10-16 10:25:04 |
+---------+--------------+------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
1 row in set (0.00 sec)
```

However, when attempting to `/login`, our flask log indicates the following error:

```bash
[2017-10-16 06:25:16,878] {/usr/local/lib/python2.7/dist-packages/flask/app.py:1560} ERROR - Exception on /login [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1632, in finalize_request
    response = self.process_response(response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1858, in process_response
    self.save_session(ctx.session, response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 924, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/vagrant/brain/cache/session.py", line 93, in save_session
    int(redis_exp.total_seconds())
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 1093, in setex
    return self.execute_command('SETEX', name, time, value)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 573, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 582, in read_response
    raise response
ResponseError: value is not an integer or out of range
```

**Note:** we also have additional [errors](https://travis-ci.org/jeff1evesque/machine-learning/builds/288390134#L5348-L5359), indicated by a corresponding travis build.

**Comment by jeff1evesque** [comment]
37bdd7c: we changed the order of our arguments in `self.redis.setex()`, per @desprit's [comment](https://github.com/andymccurdy/redis-py/issues/260#issuecomment-286303787).  Now, we were able to login, without flask generating the [above](https://github.com/jeff1evesque/machine-learning/issues/2868#issuecomment-336846732), or any other errors. However, we need to verify in redis, a corresponding login entry is created, for the duration of a `/login` session.  Additionally, we need to verify that no cookies are created, during `/login`.

**Comment by jeff1evesque** [comment]
We'll take this opportunity to write a separate `live_server/pytest_user_session.py`, with the intention to validate whether a proper redis entry is created during `/login`, and removed during `/logout`. By current pytest implementation, we'll have to simulate both `/login`, and `/logout` around this test, since the corresponding `live_server` test will only exist during duration of the check.

**Comment by jeff1evesque** [comment]
We may consider leveraging our [`query.py`](https://github.com/jeff1evesque/machine-learning/blob/82f2f1413b4b4ba6756649dc8bb855499a89d37a/brain/cache/query.py), to query redis, for our corresponding authentication session pytest.

**Comment by jeff1evesque** [comment]
The current errors we are receiving is likely because the flask `current_app` has not been instantiated. So, attempting to access flask variables, will successively fail.

**Comment by jeff1evesque** [comment]
2924596: we adjusted the order or our `setex` arguments, in accordance to the `StrictRedis` [documentation](http://redis-py.readthedocs.io/en/latest/#redis.StrictRedis.setex).

**Comment by jeff1evesque** [comment]
9f1c5dc: as stated in the corresponding [pull request](https://github.com/jeff1evesque/machine-learning/pull/3073#issuecomment-337790946), we will forgo such a granular unit test, for the interim time.

**Comment by jeff1evesque** [comment]
The attempted granular unit testing, can be continued via #2869.
