### ISSUE TITLE
Determine programmatic user login validation

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/machine-learning#2869]
We need determine a secured solution to validate users who are submitting data via the `post` requests (i.e. programmatic api).  Otherwise, upon completion of #2726, any anonymous (or validated logged-in) user, could provide `post` requests, and impersonate another user, by simply providing the corresponding userid, in the supplied `post` request.  We should also take the opportunity to write associated unit tests.

**Comment by jeff1evesque** [comment]
We need to determine if flask authentication, via from `session` (i.e. `from flask import session`), can `return` a cookie back to the client (non-browser), which later can be supplied back to the application, as a means to verify that the corresponding `POST` request is a validated `session`.

**Comment by jeff1evesque** [comment]
We can always access `session.sid` during the life cycle of our application, if the user is `/login`. For example, when a user authenticates, via a programmatic-api (i.e. `POST` request), we can return the redis key, via `session.sid`.  On subsequent requests, the same user can supply their cookie value (i.e. `session.sid`), to the backend, and be allowed for further their request, as an authenticated user.

**Note:** the `sid` is defined in the `RedisSessionInterface` class:

```python
    def open_session(self, app, request):
        sid = request.cookies.get(app.session_cookie_name)
```

And, made available through the `RedisSession` class from the same [`session.py`](https://github.com/jeff1evesque/machine-learning/blob/master/brain/cache/session.py):

```python
class RedisSession(CallbackDict, SessionMixin):
    def __init__(self, initial=None, sid=None, new=False):
        def on_update(self):
            self.modified = True

        CallbackDict.__init__(self, initial, on_update)
        self.sid = sid
        self.new = new
        self.modified = False
```

**Comment by jeff1evesque** [comment]
ae3a216: we reverted `val` per [documentation](http://redis-py.readthedocs.io/en/latest/#redis.StrictRedis.setex).

**Comment by jeff1evesque** [comment]
450b41a: we've create an initial `login.rst`, which discusses the potential of the programmatic `/login` rest endpoint, which allows a validated request, to `return` a corresponding authenticated token, which can be used on successive requests.

**Comment by jeff1evesque** [comment]
We need to perform the following:

- ensure proper flask-jwt token syntax integration with flask
- remove the ability of users to provide their username from the `properties` of corresponding dataset
  - user information, should be supplied via authenticated token
- add supplementary documentation, based on the latter two items

**Comment by jeff1evesque** [comment]
The following syntax, in our [`views.py`](https://github.com/jeff1evesque/machine-learning/blob/a12f1e85bc435e12482b3835c8360ec37574aaa5/interface/views.py#L52-L53), doesn't seem to be properly wired up to our `blueprint`:

```python
...
# local variables
blueprint = Blueprint(
    'name',
    __name__,
    template_folder='interface/templates',
    static_folder='interface/static'
)

# setup the flask-jwt-extended extension
jwt = JWTManager(blueprint)
...
```

This is causing the side effects we are noticing, on corresponding travis [builds](https://travis-ci.org/jeff1evesque/machine-learning/builds/296569202#L5402-L5416):

```bash
Traceback (most recent call last):

  File "app.py", line 16, in <module>

    from factory import create_app

  File "/var/machine-learning/factory.py", line 20, in <module>

    from interface.views import blueprint

  File "/var/machine-learning/interface/views.py", line 54, in <module>

    jwt = JWTManager(blueprint)

  File "/usr/local/lib/python2.7/dist-packages/flask_jwt_extended/jwt_manager.py", line 60, in __init__

    self.init_app(app)

  File "/usr/local/lib/python2.7/dist-packages/flask_jwt_extended/jwt_manager.py", line 74, in init_app

    self._set_default_configuration_options(app)

  File "/usr/local/lib/python2.7/dist-packages/flask_jwt_extended/jwt_manager.py", line 139, in _set_default_configuration_options

    app.config.setdefault('JWT_TOKEN_LOCATION', ['headers'])

AttributeError: 'Blueprint' object has no attribute 'config'

Error response from daemon: lstat /var/lib/docker/aufs/mnt/3d305cc1b6c48dd4cf37dc1eb1561bf1da1124788e057e7e17b6c4e4fef9ca50/var/machine-learning/.coverage: no such file or directory
```

**Comment by jeff1evesque** [comment]
017a9b0: we'll need to pass the results of `current_user = get_jwt_identity()` from the `/load-data` endpoint, to successive endpoints, in order to properly store the corresponding dataset, in such a way, that it can be associated with the user who performed the operation. This will be a better solution, then having the corresponding dataset file contain the user's `uid`.

**Comment by jeff1evesque** [comment]
We need to make the following adjustments:

- move current programmatic-api datasets under `anonymous/`
- duplicate programmatic-api dataset from `anonymous/` to `authenticated/`
  - make necessary collection name changes
- move our current unit tests, under `anonymous/` directory
  - adjust the `with open()` within `get_sample_json` for each pytest file, to account adjust dataset directory
  - get flask-jwt token during `/login`
  - supply token to `data_new`, and `data_append`
- duplicate the latter `anonymous/` directory as `authenticated/`
  - adjust the `with open()` within `get_sample_json` for each pytest file, to account adjust dataset directory
  - get flask-jwt token during `/login`
  - supply token to `data_new`, and `data_append`
- recursively fix `doc/` references for the above adjusted datasets, and unit tests
- fix `README.md` references for the above adjusted datasets, and unit tests

**Comment by jeff1evesque** [comment]
Rather than allowing this issue to grow, beyond it's initial scope, we will continue with more explicit segregated unit tests, with the intention to cover tests for authenticated users, via a dedicated #3095.
