### ISSUE TITLE
Fix json dataset submission on web-interface

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/machine-learning#3099]
We are able to submit a json dataset, through the `/session/data-new` web-interface. However, upon successive attempt, to generate a model, the browser returns a `500` http error, in the browser console.

**Comment by jeff1evesque** [comment]
We have found out why we are unable to complete a `model_generate` session, since the preceding `data_new` session, does not properly `insert` the corresponding `datasets` to our database.  Specifically, we have added the following temporary `raise` statements, to our current `base_data.py`:

```python
    def save_premodel_dataset(self):
        '''

        This method saves the entire the dataset collection, as a json
        document, into the nosql implementation.

        '''

        # local variables
        entity = Entity()
        cursor = Collection()
        collection = self.premodel_data['properties']['collection']
        collection_adjusted = collection.lower().replace(' ', '_')
        collection_count = entity.get_collection_count(self.uid)
        document_count = cursor.query(collection_adjusted, 'count_documents')

        # enfore collection limit: oldest collection name is obtained from the
        #     sql database. Then, the corresponding collection (i.e. target) is
        #     removed from the nosql database.
        if (
            not self.uid and
            collection_count and
            collection_count['result'] >= self.max_collection and
            collection_adjusted
        ):
            target = entity.get_collections(self.uid)['result'][0]
            cursor.query(target, 'drop_collection')
            entity.remove_entity(self.uid, target)
            collection_count = entity.get_collection_count(self.uid)
            document_count = cursor.query(collection_adjusted, 'count_documents')

        # save dataset
        if (
            collection_adjusted and
            collection_count and
            collection_count['result'] < self.max_collection and
            document_count and
            document_count['result'] < self.max_document
        ):
            current_utc = datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S")
            self.premodel_data['properties']['datetime_saved'] = current_utc
            document = {
                'properties': self.premodel_data['properties'],
                'dataset': self.dataset
            }

            response = cursor.query(
                collection_adjusted,
                'insert_one',
                document
            )
            raise Exception('brain/session/base_data.py, repr(response); ' + repr(response) + ', repr(document): ' + repr(document))

        else:
            response = None
            raise Exception('brain/session/base_data.py, dataset not saved')

        # return result
        if response and response['error']:
            self.list_error.append(response['error'])
            return {'result': None, 'error': response['error']}

        elif response and response['result']:
            return {'result': response['result'], 'error': None}

        else:
            return {'result': None, 'error': 'no dataset provided'}
```

When we attempt to save a corresponding sample json dataset:

![failed-data-new](https://user-images.githubusercontent.com/2907085/32991162-342d981e-cd04-11e7-819e-ea40050303f4.JPG)

We notice that our `flask.log` reports the following:

```bash
[2017-11-19 08:27:55,313] {/usr/local/lib/python2.7/dist-packages/flask/app.py:1560} ERROR - Exception on /load-data [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/interface/views_web.py", line 94, in load_data
    response = loader.load_data_new()
  File "/vagrant/brain/load_data.py", line 76, in load_data_new
    session.save_premodel_dataset()
  File "/vagrant/brain/session/base_data.py", line 129, in save_premodel_dataset
    raise Exception('brain/session/base_data.py, repr(response); ' + repr(response) + ', repr(document): ' + repr(document))
Exception: brain/session/base_data.py, repr(response); {'status': True, 'result': <pymongo.results.InsertOneResult object at 0x7fd46154e0a0>, 'error': None}, repr(document): {'_id': ObjectId('5a1186db9bd56c088da81c72'), 'properties': {'stream': False, 'session_type': u'data_new', 'collection': u'collection-2', 'datetime_saved': '2017-11-19T13:27:55', 'dataset_type': u'file_upload', 'model_type': u'svm', 'session_name': u'test'}, 'dataset': []}
```

**Comment by jeff1evesque** [comment]
We further adjusted, and moved the previous `raise` statements within `base_data.py`:

```python
    def convert_dataset(self):
        '''

        This method converts the supplied csv, or xml file upload(s) to a
            uniform dict object.

        '''

        # convert to dictionary
        response = dataset2dict(self.model_type, self.premodel_data)
        raise Exception('brain/session/base_data.py, convert_dataset: ' + repr(response))

        # return result
        if response['error']:
            self.list_error.append(response['error'])
        else:
            self.dataset = response['dataset']
```

Submitting another trivial request to the `data_new` session, logged the following within `flask.log`:

```bash
[2017-11-19 08:56:01,178] {/usr/local/lib/python2.7/dist-packages/flask/app.py:1560} ERROR - Exception on /load-data [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/interface/views_web.py", line 94, in load_data
    response = loader.load_data_new()
  File "/vagrant/brain/load_data.py", line 75, in load_data_new
    session.convert_dataset()
  File "/vagrant/brain/session/base_data.py", line 154, in convert_dataset
    raise Exception('brain/session/base_data.py, convert_dataset: ' + repr(response))
Exception: brain/session/base_data.py, convert_dataset: {'settings': {'stream': False, 'session_type': u'data_new', 'collection': u'collection-3', 'dataset_type': u'file_upload', 'model_type': u'svm', 'session_name': u'test'}, 'error': None, 'dataset': []}
```
