### ISSUE TITLE
Ensure flask logs errors to designated file

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/machine-learning#3100]
Our previous working logic, in our [`factory.py`](https://github.com/jeff1evesque/machine-learning/blob/e8d38b2c7085d5f4fcfbcaf7d7486ac56260310e/factory.py#L128-L145):

```python
    # log handler: requires the below logger
    formatter = logging.Formatter(
        "[%(asctime)s] {%(pathname)s:%(lineno)d} "
        "%(levelname)s - %(message)s"
    )
    handler = RotatingFileHandler(
        LOG_PATH,
        maxBytes=10000000,
        backupCount=5
    )
    handler.setLevel(HANDLER_LEVEL)
    handler.setFormatter(formatter)
    app.logger.addHandler(handler)

    # logger: complements the log handler
    log = logging.getLogger('werkzeug')
    log.setLevel(logging.DEBUG)
    log.addHandler(handler)

    # return
return app
```

No longer logs flask errors, even when making a deliberate trivial syntax error, anywhere in the application.

**Comment by jeff1evesque** [comment]
We've attempted to comment out the addition of flask-jwt-extended (token authentication), as well as the redis cache integration in our `factory.py`.  However, our attempts to suppress these functionalities, did not produce any insights, or clues on how to further debug our recent problems.  We know this problem was fairly recent. Therefore, we'll attempt to iteratively `git checkout` previous branches, until we discover that our flask logs become functional.

**Comment by jeff1evesque** [comment]
It seems we may have made an error. The following temporarily adjustments:

```bash
jeff1evesque@XXXXXXX YYYYYYY /path/to/machine-learning (master)
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   factory.py
        modified:   interface/views.py

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        src/js/

no changes added to commit (use "git add" and/or "git commit -a")

jeff1evesque@XXXXXXX YYYYYYY /path/to/machine-learning (master)
$ git diff interface/
diff --git a/interface/views.py b/interface/views.py
index db0ad58..82e75bd 100644
--- a/interface/views.py
+++ b/interface/views.py
@@ -32,11 +32,11 @@ from brain.database.prediction import Prediction
 from brain.converter.crypto import hash_pass, verify_pass
 from brain.database.entity import Entity
 from brain.database.dataset import Collection
-from flask_jwt_extended import (
-    create_access_token,
-    jwt_optional,
-    get_jwt_identity
-)
+#from flask_jwt_extended import (
+#    create_access_token,
+#    jwt_optional,
+#    get_jwt_identity
+#)

 # local variables
 blueprint = Blueprint(
@@ -66,7 +66,6 @@ def index(path):


 @blueprint.route('/load-data', methods=['POST'], endpoint='load_data')
-@jwt_optional
 def load_data():
     '''

@@ -85,7 +84,8 @@ def load_data():
     '''

     if request.method == 'POST':
-        current_user = get_jwt_identity()
+#        current_user = get_jwt_identity()
+        current_user = 'jeff1evesque'

         # programmatic-interface
         if request.get_json():
@@ -119,6 +119,7 @@ def load_data():

         # web-interface: get submitted form data
         if request.form:
+            print(jeff)
             settings = request.form
             sender = Settings(settings, files)
             data_formatted = sender.restructure()
@@ -198,10 +199,11 @@ def login():
                     # notification: verify password
                     if verify_pass(str(password), hashed_password):
                         # create and serialize uid token
-                        access_token = create_access_token(identity=uid)
-
-                        # return status
-                        return json.dumps({'status': 0, 'access_token': access_token})
+#                        access_token = create_access_token(identity=uid)
+#
+#                        # return status
+#                        return json.dumps({'status': 0, 'access_token': access_token})
+                        return json.dumps({'status': 100, 'access_token': 'blah'})

                     # notification: incorrect password
                     else:

jeff1evesque@XXXXXXX YYYYYYY /path/to/machine-learning (master)
$ git diff factory.py
diff --git a/factory.py b/factory.py
index 66186f7..f8f129b 100644
--- a/factory.py
+++ b/factory.py
@@ -18,7 +18,7 @@ from flask import Flask, g
 from logging.handlers import RotatingFileHandler
 from brain.cache.session import RedisSessionInterface
 from interface.views import blueprint
-from flask_jwt_extended import JWTManager
+#from flask_jwt_extended import JWTManager


 # application factory
@@ -68,12 +68,12 @@ def create_app(args={'prefix': '', 'settings': ''}):
             static_folder='interface/static',
         )

-    # replace default cookie session with server-side redis
-    app.session_interface = RedisSessionInterface(
-        cache['host'],
-        cache['port'],
-        cache['db']
-    )
+#    # replace default cookie session with server-side redis
+#    app.session_interface = RedisSessionInterface(
+#        cache['host'],
+#        cache['port'],
+#        cache['db']
+#    )

     # secret key: used for maintaining flask sessions
     app.secret_key = application['security_key']
@@ -81,8 +81,8 @@ def create_app(args={'prefix': '', 'settings': ''}):
     # register blueprint
     app.register_blueprint(blueprint)

-    # set the flask-jwt-extended extension
-    JWTManager(app)
+#    # set the flask-jwt-extended extension
+#    JWTManager(app)

     # local logger: used for this module
     root = general['root']
```

Produced the following expected traceback:

```bash
[2017-11-06 21:53:49,213] {/usr/local/lib/python2.7/dist-packages/flask/app.py:1560} ERROR - Exception on /load-data [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/interface/views.py", line 122, in load_data
    print(jeff)
NameError: global name 'jeff' is not defined
```

**Comment by jeff1evesque** [comment]
It seems we've found the culprit. When `from flask_jwt_extended import JWTManager` is commented out, from our `factory.py`, then syntax errors are logged, to our `flask.log`. However, keeping the corresponding `import` intact, results with syntax errors being ignored, and not logged.

**Comment by jeff1evesque** [comment]
We should consider adding a unit test, such that the corresponding `POST` request, generates a trivial error, resulting with an entry in our `flask.log`. So, we'll need to device a way to read the generated `flask.log`.

**Comment by jeff1evesque** [comment]
We need to duplicate the same changes, and enhancements being made on the `vagrant` environment, as the `docker` environment.  Additionally, we'll need to make reference of these changes in our `README.md`, and `doc/` respectively. Specifically, we'll need to inform users the different endpoints for the corresponding web-interface, as well as the programmatic-api.

**Comment by jeff1evesque** [comment]
We'll also need to create a second instance of `blueprint`, in our `interface/views.py`, to further segregate the web-interface, with the programmatic-api.  This will allow us to conditionally implement the two different `blueprint`s from our `factory.py`, to allow a set of dedicated routes for each implementation.

**Comment by jeff1evesque** [comment]
dbba524: we have taken the initiative to restrict the programmatic-api, to users who have successfully authenticated, by supplying a valid [flask-jwt-extended]() token. This change may have been more appropriate as it's own designated issue. So, we'll need to remember to mention this, in the mini 0.6.1 [release](https://github.com/jeff1evesque/machine-learning/tags) notes, along with the [0.6.1](https://github.com/jeff1evesque/machine-learning/milestone/11) milestone description.

**Comment by jeff1evesque** [comment]
Without the following temporary adjustments, the web-interface will generate a `502` error:

```bash
jeff1evesque@XXXXXXX YYYYYYY /path/to/machine-learning (bug-3100)
$ git diff factory.py
diff --git a/factory.py b/factory.py
index ef0f054..f803227 100644
--- a/factory.py
+++ b/factory.py
@@ -17,7 +17,7 @@ import logging
 from flask import Flask, g
 from logging.handlers import RotatingFileHandler
 from brain.cache.session import RedisSessionInterface
-from interface.views_api import blueprint_api
+#from interface.views_api import blueprint_api
 from interface.views_web import blueprint_web
 from flask_jwt_extended import JWTManager

@@ -55,15 +55,19 @@ def create_app(args={'instance': 'web'}):
         validate_password = settings['validate_password']

     # programmatic-api: set the flask-jwt-extended extension
-    if args['instance'] == 'api':
-        app = Flask(__name__)
-        app.secret_key = application['security_key']
-        app.config['JWT_SECRET_KEY'] = application['security_key']
-        app.register_blueprint(blueprint_api)
-        JWTManager(app)
-
-    # web-interface: replace default cookie session with server-side redis
-    else:
+#    if args['instance'] == 'api':
+#        app = Flask(__name__)
+#        app.secret_key = application['security_key']
+#        app.config['JWT_SECRET_KEY'] = application['security_key']
+#        app.register_blueprint(blueprint_api)
+#        JWTManager(app)
+#
+#        # allow error logging
+#        app.config['PROPAGATE_EXCEPTIONS'] = False
+#
+#    # web-interface: replace default cookie session with server-side redis
+#    else:
+    if True:
         app = Flask(
             __name__,
             template_folder='interface/templates',
@@ -141,9 +145,6 @@ def create_app(args={'instance': 'web'}):
     log.setLevel(logging.DEBUG)
     log.addHandler(handler)

-    # allow error logging
-    app.config['PROPAGATE_EXCEPTIONS'] = False
-
     # return
     return app
```

So, we'll need to check whether the `blueprint_api` has some syntax errors, or whether it's attempted implementation, within `factory.py` has some underlying problems.

**Comment by jeff1evesque** [comment]
We have manually checked, by implementing `print(jeff)` in our `/load-data` route, which triggered an exception, a corresponding log entry, in our `flask.log`, for the web-interface. However, to be sure, we'll need to design a corresponding unit-test for our programmatic-api. This means, the `docker` puppet environment will need respective definitions.

**Comment by jeff1evesque** [comment]
Since we've enforced the `jwt_required` decorator, on all of our programmatic-api routes (except `/login`), we'll need to `/login` before our pytests, in order to obtain the authentication token, to be supplied within the header, on successive `POST` requests.

**Comment by jeff1evesque** [comment]
We need to make adjustments to our `load_data.py`:

```python
        # flask jwt-token user
        elif username:
            uid = Account().get_uid(username)
            if uid['result']:
                self.uid = uid['result']
            else:
                self.uid = current_app.config.get('USER_ID')
```

Since, our `views_api.py`, seems to print the `uid` instead of the actual username:

```python
@blueprint_api.route('/load-data', methods=['POST'], endpoint='load_data')
@jwt_required
def load_data():
    '''

    This method returns the computed data, resulting from one of the following
    implemented session:

        - data_new
        - data_append
        - model_predict
        - model_generate

    Note: more information on flask-jwt partially protecting routes:

        http://flask-jwt-extended.readthedocs.io/en/latest/optional_endpoints.html

    '''

    if request.method == 'POST':
        current_user = get_jwt_identity()

        # programmatic-interface
        if request.get_json():
            print('request.get_json(): ' + repr(request.get_json()) + ', current_user: ' + repr(current_user))
            raise Exception('views_api.py, load_data')
            # send data to brain
            loader = Load_Data(request.get_json(), current_user)
            if loader.get_session_type()['session_type']:
                session_type = loader.get_session_type()['session_type']
```
This means, we'll likely need to remove `get_uid`, from our `brain/database/account.py`.

**Comment by jeff1evesque** [comment]
9966b69d: we have incorrectly removed `get_uid`, since it is required by our `views_api.py` (as indicated by our travis [build](https://travis-ci.org/jeff1evesque/machine-learning/builds/303807879#L5618-L5620)), as well as our `views_web.py`.

**Comment by jeff1evesque** [comment]
Our programmatic rest-api seems to be working, and confirmed by the latest corresponding travis [build](https://travis-ci.org/jeff1evesque/machine-learning/builds/304101899). However, we still need to ensure the following:

- web-interface is runnable
- ensure errors logs to `flask.log`
  - web-interface
  - programmatic rest-api
- adjust `doc/`
- adjust `README.md`

**Comment by jeff1evesque** [comment]
Our web-interface has been tested for the csv, and xml datasets. These cases were able to generate a model, then a corresponding prediction. However, the json case, still generate errors as indicated by #3099. Specifically, our corresponding `flask.log` has logged the following:

```bash
[2017-11-18 20:19:53,802] {/usr/local/lib/python2.7/dist-packages/flask/app.py:1560} ERROR - Exception on /load-data [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/interface/views_web.py", line 98, in load_data
    response = loader.load_model_generate()
  File "/vagrant/brain/load_data.py", line 151, in load_model_generate
    session.generate_model()
  File "/vagrant/brain/session/model_generate.py", line 69, in generate_model
    self.list_error
  File "/vagrant/brain/session/model/sv.py", line 84, in generate
    clf.fit(grouped_features, encoded_labels)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/svm/base.py", line 139, in fit
    X = check_array(X, accept_sparse='csr', dtype=np.float64, order='C')
  File "/usr/local/lib/python2.7/dist-packages/sklearn/utils/validation.py", line 367, in check_array
    % (n_features, shape_repr, ensure_min_features))
ValueError: Found array with 0 feature(s) (shape=(1, 0)) while a minimum of 1 is required.
```

So, we'll ignore the above error per #3099, and proceed with the following:

- ensure errors log to designated flask.log
  - programmatic rest-api
- adjust `doc/`
- adjust `README.md`

**Comment by jeff1evesque** [comment]
We submitted a incorrect trivial `POST` request, to our programmatic rest-api:

![rest-incorrect](https://user-images.githubusercontent.com/2907085/32986504-2673c8c8-cca1-11e7-9fe4-563a79789c44.JPG)

Which generated a log, into the same `flask.log`:

```bash
[2017-11-18 20:41:09,203] {/usr/local/lib/python2.7/dist-packages/flask/app.py:1560} ERROR - Exception on /load-data [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1630, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1725, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
```
