### ISSUE TITLE
Update docker unit testing containers

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/machine-learning#3184]
Our current containers, available on dockerhub, is inconsistent with requirements of our flask application. Specifically, there have been issues (including #1919) that have adjusted the build + application requirements. These adjustments, have not been taken into account with the current docker containers. For example, when attempting to run a local unit tests, with respect to development on #1919:

```bash
root@trusty64:/vagrant/test# ./unit-tests
...
Digest: sha256:1d68a005dc2da786b21d29f16d0bd90ce7d50110a2d4a8681e3b2d0a7de72afe
Status: Downloaded newer image for jeff1evesque/ml-mariadb:1.0
ae4ea9ab14405d9500292ea1cd26479183e8f4d3fe710684fc81f47c89590048
Successfully added user: {
        "user" : "authenticated",
        "roles" : [
                "readWrite",
                "userAdmin",
                "dbAdmin",
                {
                        "role" : "readWrite",
                        "db" : "dataset"
                },
                {
                        "role" : "userAdmin",
                        "db" : "dataset"
                },
                {
                        "role" : "dbAdmin",
                        "db" : "dataset"
                }
        ]
}
2018-01-18T20:21:12.128-0500 E -        [main] file [mongodb://mongodb:27017] doesn't exist
failed to load: mongodb://mongodb:27017
mongodb
Traceback (most recent call last):
  File "app.py", line 16, in <module>
    from factory import create_app
  File "/var/machine-learning/factory.py", line 20, in <module>
    from interface.views_api import blueprint_api
  File "/var/machine-learning/interface/views_api.py", line 22, in <module>
    from brain.load_data import Load_Data
  File "/var/machine-learning/brain/load_data.py", line 12, in <module>
    from brain.session.data_append import DataAppend
  File "/var/machine-learning/brain/session/data_append.py", line 16, in <module>
    from brain.session.base_data import BaseData
  File "/var/machine-learning/brain/session/base_data.py", line 14, in <module>
    from brain.session.base import Base
  File "/var/machine-learning/brain/session/base.py", line 14, in <module>
    from brain.validator.settings import Validator
  File "/var/machine-learning/brain/validator/settings.py", line 9, in <module>
    from brain.schema.session import validate_data_new
  File "/var/machine-learning/brain/schema/session.py", line 10, in <module>
    from voluptuous import Schema, Required, Optional, All, Any, In, Length
ImportError: No module named voluptuous
Error response from daemon: Could not find the file /var/machine-learning/.coverage in container webserver-pytest
```

**Note:** we should use this issue, to ensure the corresponding manual linter also works.

**Comment by jeff1evesque** [comment]
We will rebuild our containers using the following syntax:

```bash
sudo docker build -f default.dockerfile -t ml-base.
sudo docker run --name default -d ml-base
docker commit -m "remove git repo for 'ml-base'" -a 'jeff1evesque' default jeff1evesque/ml-base:0.7
docker login
docker push jeff1evesque/ml-base
```

**Note:** we will rebuild all our containers, then create `ml-base`, which will be used by #2935, and will phase out `ml-default`. Additionally, we will tag each of the updated containers by the current `0.7`, which represents the current milestone.

**Comment by jeff1evesque** [comment]
Our `unit-tests`, produces the following traceback:

```bash
[...OMITTED-TRACE...]
2018-03-03T18:32:25.982-0500 E QUERY    [thread1] Error: couldn't add user: not authorized on                                                                                                  admin to execute command { createUser: "authenticated", pwd: "xxx", roles: [ "readWrite", "u                                                                                                 serAdmin", "dbAdmin", { role: "readWrite", db: "dataset" }, { role: "userAdmin", db: "dataset                                                                                                 " }, { role: "dbAdmin", db: "dataset" } ], digestPassword: false, writeConcern: { w: "majorit                                                                                                 y", wtimeout: 5000.0 } } :
_getErrorWithCode@src/mongo/shell/utils.js:25:13
DB.prototype.createUser@src/mongo/shell/db.js:1267:15
@(shell eval):1:1

mongodb
============================= test session starts ==============================
platform linux2 -- Python 2.7.6, pytest-3.4.1, py-1.5.2, pluggy-0.6.0
rootdir: /var/machine-learning/test/live_server, inifile: pytest.ini
plugins: cov-2.4.0, flask-0.10.0
collected 48 items

test/live_server/1_authentication/pytest_1_crypto.py .                   [  2%]
test/live_server/1_authentication/pytest_2_account_registration.py E     [  4%]
test/live_server/1_authentication/pytest_3_validate_password.py .        [  6%]
test/live_server/1_authentication/pytest_4_user_login.py E               [  8%]
test/live_server/1_authentication/pytest_5_user_logout.py E              [ 10%]
test/live_server/2_database/pytest_svm_dbmax.py EEEEEEEEEE               [ 31%]
test/live_server/2_database/pytest_svr_dbmax.py EEEEEEEEEE               [ 52%]
test/live_server/3_programmatic_interface/dataset_url/pytest_svm_dataset_url.py E [ 54%]
EEE                                                                      [ 60%]
test/live_server/3_programmatic_interface/dataset_url/pytest_svr_dataset_url.py E [ 62%]
EEE                                                                      [ 68%]
test/live_server/3_programmatic_interface/file_upload/pytest_svm_file_upload.py E [ 70%]
EEE                                                                      [ 77%]
test/live_server/3_programmatic_interface/file_upload/pytest_svr_file_upload.py E [ 79%]
EEE                                                                      [ 85%]
test/live_server/3_programmatic_interface/results/pytest_1_svm_prediction.py E [ 87%]
EE                                                                       [ 91%]
test/live_server/3_programmatic_interface/results/pytest_2_svr_prediction.py E [ 93%]
EE                                                                       [ 97%]
test/live_server/3_programmatic_interface/results/pytest_3_all_prediction_titles.py E [100%]

---------- coverage: platform linux2, python 2.7.6-final-0 -----------
Name                                                                                  Stmts                                                                                                    Miss  Cover
---------------------------------------------------------------------------------------------                                                                                                 ------------
__init__.py                                                                               0                                                                                                       0   100%
app.py                                                                                   12                                                                                                      12     0%
brain/__init__.py                                                                         0                                                                                                       0   100%
brain/cache/__init__.py                                                                   0                                                                                                       0   100%
brain/cache/hset.py                                                                      22                                                                                                      22     0%
brain/cache/model.py                                                                     34                                                                                                      34     0%
brain/cache/query.py                                                                     87                                                                                                      87     0%
brain/cache/session.py                                                                   51                                                                                                      51     0%
brain/cache/settings.py                                                                  14                                                                                                      14     0%
brain/converter/__init__.py                                                               0                                                                                                       0   100%
brain/converter/crypto.py                                                                45                                                                                                      12    73%
brain/converter/format/__init__.py                                                        0                                                                                                       0   100%
brain/converter/format/csv2dict.py                                                       21                                                                                                      21     0%
brain/converter/format/xml2dict.py                                                       19                                                                                                      19     0%
brain/converter/md5.py                                                                    9                                                                                                       9     0%
brain/converter/model.py                                                                 12                                                                                                      12     0%
brain/converter/operation.py                                                             45                                                                                                      45     0%
brain/converter/settings.py                                                              50                                                                                                      50     0%
brain/database/__init__.py                                                                0                                                                                                       0   100%
brain/database/account.py                                                                55                                                                                                      55     0%
brain/database/dataset.py                                                                16                                                                                                      16     0%
brain/database/entity.py                                                                 60                                                                                                      60     0%
brain/database/model_type.py                                                             17                                                                                                      17     0%
brain/database/prediction.py                                                             89                                                                                                      89     0%
brain/database/query.py                                                                 125                                                                                                     125     0%
brain/database/session.py                                                                30                                                                                                      30     0%
brain/database/settings.py                                                               46                                                                                                      46     0%
brain/load_data.py                                                                       75                                                                                                      75     0%
brain/session/__init__.py                                                                 0                                                                                                       0   100%
brain/session/base.py                                                                    33                                                                                                      33     0%
brain/session/base_data.py                                                               59                                                                                                      59     0%
brain/session/data/__init__.py                                                            0                                                                                                       0   100%
brain/session/data/dataset.py                                                            61                                                                                                      61     0%
brain/session/data_append.py                                                             29                                                                                                      29     0%
brain/session/data_new.py                                                                27                                                                                                      27     0%
brain/session/model/__init__.py                                                           0                                                                                                       0   100%
brain/session/model/sv.py                                                                44                                                                                                      44     0%
brain/session/model_generate.py                                                          26                                                                                                      26     0%
brain/session/model_predict.py                                                           14                                                                                                      14     0%
brain/session/predict/__init__.py                                                         0                                                                                                       0   100%
brain/session/predict/sv.py                                                              22                                                                                                      22     0%
brain/validator/__init__.py                                                               0                                                                                                       0   100%
brain/validator/dataset.py                                                               40                                                                                                      40     0%
brain/validator/email.py                                                                  7                                                                                                       7     0%
brain/validator/password.py                                                              43                                                                                                       8    81%
brain/validator/settings.py                                                              28                                                                                                      28     0%
factory.py                                                                               59                                                                                                      27    54%
interface/__init__.py                                                                     0                                                                                                       0   100%
interface/views_api.py                                                                  199                                                                                                     199     0%
interface/views_web.py                                                                  165                                                                                                     165     0%
log/__init__.py                                                                           0                                                                                                       0   100%
log/logger.py                                                                            84                                                                                                      84     0%
puppet/__init__.py                                                                        0                                                                                                       0   100%
puppet/environment/__init__.py                                                            0                                                                                                       0   100%
puppet/environment/docker/__init__.py                                                     0                                                                                                       0   100%
puppet/environment/docker/modules/__init__.py                                             0                                                                                                       0   100%
puppet/environment/docker/modules/mariadb/__init__.py                                     0                                                                                                       0   100%
puppet/environment/docker/modules/mariadb/scripts/__init__.py                             0                                                                                                       0   100%
puppet/environment/docker/modules/mariadb/scripts/setup_tables.py                        40                                                                                                      40     0%
puppet/environment/vagrant/__init__.py                                                    0                                                                                                       0   100%
puppet/environment/vagrant/modules/__init__.py                                            0                                                                                                       0   100%
puppet/environment/vagrant/modules/mariadb/__init__.py                                    0                                                                                                       0   100%
puppet/environment/vagrant/modules/mariadb/scripts/__init__.py                            0                                                                                                       0   100%
puppet/environment/vagrant/modules/mariadb/scripts/setup_tables.py                       40                                                                                                      40     0%
test/live_server/1_authentication/pytest_1_crypto.py                                     15                                                                                                       2    87%
test/live_server/1_authentication/pytest_2_account_registration.py                       21                                                                                                      16    24%
test/live_server/1_authentication/pytest_3_validate_password.py                          16                                                                                                       2    88%
test/live_server/1_authentication/pytest_4_user_login.py                                 20                                                                                                      16    20%
test/live_server/1_authentication/pytest_5_user_logout.py                                16                                                                                                      14    13%
test/live_server/2_database/pytest_svm_dbmax.py                                         110                                                                                                      95    14%
test/live_server/2_database/pytest_svr_dbmax.py                                         110                                                                                                      95    14%
test/live_server/3_programmatic_interface/dataset_url/pytest_svm_dataset_url.py          58                                                                                                      49    16%
test/live_server/3_programmatic_interface/dataset_url/pytest_svr_dataset_url.py          48                                                                                                      39    19%
test/live_server/3_programmatic_interface/file_upload/pytest_svm_file_upload.py          58                                                                                                      49    16%
test/live_server/3_programmatic_interface/file_upload/pytest_svr_file_upload.py          48                                                                                                      39    19%
test/live_server/3_programmatic_interface/results/pytest_1_svm_prediction.py             68                                                                                                      59    13%
test/live_server/3_programmatic_interface/results/pytest_2_svr_prediction.py             67                                                                                                      58    13%
test/live_server/3_programmatic_interface/results/pytest_3_all_prediction_titles.py      36                                                                                                      29    19%
test/live_server/conftest.py                                                             19                                                                                                       7    63%
---------------------------------------------------------------------------------------------                                                                                                 ------------
TOTAL                                                                                  2664                                                                                                    2423     9%
[...OMITTED-TRACE...]
```

**Comment by jeff1evesque** [comment]
When adjusting our `unit-tests` to reference the `0.7` tag, we notice the following containers:

```bash
root@vagrant-ubuntu-trusty-64:/vagrant/test# docker ps -a
CONTAINER ID        IMAGE                           COMMAND             CREATED             STATUS                      PORTS               NAMES
c5009a4479ae        jeff1evesque/ml-webserver:0.7   "test"              11 seconds ago      Exited (1) 10 seconds ago                       webserver-pytest
7d1df723a2c8        jeff1evesque/ml-mariadb:0.7     "/bin/bash"         12 seconds ago      Exited (0) 11 seconds ago                       mariadb
9d451cb9102d        jeff1evesque/ml-webserver:0.7   "/bin/bash"         13 seconds ago      Exited (0) 12 seconds ago                       webserver
086a50db1897        jeff1evesque/ml-mongodb:0.7     "/bin/bash"         13 seconds ago      Exited (0) 11 seconds ago                       mongodb
715df6cd0d73        jeff1evesque/ml-redis:0.7       "/bin/bash"         14 seconds ago      Exited (0) 13 seconds ago                       redis
11e7145c99bd        jeff1evesque/ml-base:0.7        "/bin/bash"         14 seconds ago      Exited (0) 13 seconds ago                       base
```

This means our implementation of `docker run`, are immediately exiting after its initial run.
