### ISSUE TITLE
Define 'xml_to_json' in 'converter_json.py'

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/machine-learning#457]
We need to define the method [`xml_to_json`](https://github.com/jeff1evesque/machine-learning/blob/0a667c713eae8e07810519feafd32a505d5ff994/python/svm_json.py#L16) in `converter_json.py`.  This method will convert an `xml file` to a JSON structure.

**Comment by jeff1evesque** [comment]
We were able to add data from `sample.xml` via the *data_new* session, which appended 1 record into the `tbl_dataset_entity` table, and 21 records into the `tbl_dataset_value` table.  We save the latter session as *test*, within the *web-interface*.  Then, we proceeded with the *data_append* session, selected *test* from the *web-interface*, uploaded `sample.csv`, and proceeded with the form submission.  We noticed that, `tbl_dataset_entity` still only has one record within the table (same as the original), and `tbl_dataset_value` now has 42 records:

![tbl_entity](https://cloud.githubusercontent.com/assets/2907085/5963707/8ea527fa-a7bc-11e4-9a36-5df54261d31e.png)

![tbl_value](https://cloud.githubusercontent.com/assets/2907085/5963712/92428d94-a7bc-11e4-8fef-47bc2a7e288b.png)

**Comment by jeff1evesque** [comment]
We need to resolve the following traceback:

```bash
$ python app.py
 * Running on http://127.0.0.1:5000/
 * Restarting with reloader
'unicode' object has no attribute 'append'
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 53917)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 200, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 235, in handle_one_request
    return self.run_wsgi()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 167, in execute
    for data in application_iter:
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/debug/__init__.py", line 88, in debug_application
    app_iter = self.app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/web_interface/views.py", line 36, in load_data
    if session_type == 'data_new': response = loader.load_data_new()
  File "/var/www/brain/load_data.py", line 40, in load_data_new
    session.check()
  File "/var/www/brain/session/session_base.py", line 45, in check
    sys.exit()
SystemExit
----------------------------------------
```

**Comment by jeff1evesque** [comment]
If we implement a `print` statement as follows:

```python
...
  ## xml_to_json: convert xml to JSON object
  #
  #  @observation_label, is a list containing dependent variable labels.
  def xml_to_json(self):
    list_dataset      = []
    observation_label = []

    # convert xml file to python 'dict'
    dataset = xmltodict.parse(self.svm_file)
    print dataset
...
```

We get the following traceback subset during a `data_new* session with [`sample.xml`](https://github.com/jeff1evesque/machine-learning/blob/master/web_interface/static/data/xml/sample.xml):

```bash
...
$ python app.py
 * Running on http://127.0.0.1:5000/
 * Restarting with reloader
OrderedDict([(u'dataset', OrderedDict([(u'entity', [OrderedDict([(u'dependent-variable', u'dep-variable-1'), (u'independent-variable', [OrderedDict([(u'label', u'indep-variable-1'), (u'value', u'23.45')]), OrderedDict([(u'label', u'indep-variable-2'), (u'value', u'98.01')]), OrderedDict([(u'label', u'indep-variable-3'), (u'value', u'0.432')]), OrderedDict([(u'label', u'indep-variable-4'), (u'value', u'325')]), OrderedDict([(u'label', u'indep-variable-5'), (u'value', u'54.64')]), OrderedDict([(u'label', u'indep-variable-6'), (u'value', u'0.002')]), OrderedDict([(u'label', u'indep-variable-7'), (u'value', u'25')])])]), OrderedDict([(u'dependent-variable', u'dep-variable-2'), (u'independent-variable', [OrderedDict([(u'label', u'indep-variable-1'), (u'value', u'24.32')]), OrderedDict([(u'label', u'indep-variable-2'), (u'value', u'92.22')]), OrderedDict([(u'label', u'indep-variable-3'), (u'value', u'0.356')]), OrderedDict([(u'label', u'indep-variable-4'), (u'value', u'235')]), OrderedDict([(u'label', u'indep-variable-5'), (u'value', u'64.45')]), OrderedDict([(u'label', u'indep-variable-6'), (u'value', u'0.001')]), OrderedDict([(u'label', u'indep-variable-7'), (u'value', u'31')])])]), OrderedDict([(u'dependent-variable', u'dep-variable-3'), (u'independent-variable', [OrderedDict([(u'label', u'indep-variable-1'), (u'value', u'22.67')]), OrderedDict([(u'label', u'indep-variable-2'), (u'value', u'101.21')]), OrderedDict([(u'label', u'indep-variable-3'), (u'value', u'0.832')]), OrderedDict([(u'label', u'indep-variable-4'), (u'value', u'427')]), OrderedDict([(u'label', u'indep-variable-5'), (u'value', u'75.45')]), OrderedDict([(u'label', u'indep-variable-6'), (u'value', u'0.002')]), OrderedDict([(u'label', u'indep-variable-7'), (u'value', u'24')])])])])]))])
'unicode' object has no attribute 'append'
----------------------------------------
...
```

**Comment by jeff1evesque** [comment]
The above commits resolves our problem, with the exception of the case when a user attempts to upload two or more [distinct](https://github.com/jeff1evesque/machine-learning/issues/1542#issue-59557637) file-uploads.
