### ISSUE TITLE
Create backend logic to parse contents of URL

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/machine-learning#5]
We will create `python/xml_retriever.py` as a generic class that will take two parameters:

- the URL of the xml document to parse
- an object containing the xml attributes to parse from the *xml document*

This class, after being instantiated will return an object.  This return object will be the important *xml attributes* we wanted to parse for (as defined by the second parameter of this class).

**Comment by jeff1evesque** [comment]
The above remarks are no longer valid, for the same reasons as follows:

 - https://github.com/jeff1evesque/machine-learning/issues/1290#issuecomment-140224248

Therefore, we need to create generic logic, that will parse the contents of a webpage, for the following cases:

- csv
- xml
- json

**Comment by jeff1evesque** [comment]
When we submit a *data new* session:

![screen shot 2016-09-10 at 7 39 44 pm](https://cloud.githubusercontent.com/assets/2907085/18414189/778edb58-778e-11e6-88c0-33f0964aebf7.png)

with the following url references:

- https://raw.githubusercontent.com/jeff1evesque/machine-learning/master/interface/static/data/json/web_interface/svm-1.json
- https://raw.githubusercontent.com/jeff1evesque/machine-learning/master/interface/static/data/json/web_interface/svm-1.json
- https://raw.githubusercontent.com/jeff1evesque/machine-learning/master/interface/static/data/json/web_interface/svm.json

we get the following traceback error upon form submission:

```bash
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ python app.py
[{'type': u'json', 'file': <Response [200]>, 'filename': u'svm.json'}, {'type': u'json', 'file': <Response [200]>, 'filename': u'svm.json'}]
[2016-09-10 19:41:53,177] ERROR in app: Exception on /load-data/ [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/interface/views.py", line 122, in load_data
    response = loader.load_data_new()
  File "/vagrant/brain/load_data.py", line 70, in load_data_new
    session.dataset_to_dict(session_id)
  File "/vagrant/brain/session/base_data.py", line 173, in dataset_to_dict
    response = dataset_dictionary(id_entity, self.model_type, self.upload)
  File "/vagrant/brain/session/data/dataset_to_dict.py", line 29, in dataset_dictionary
    json_upload = upload['dataset']['json_string']
KeyError: 'json_string'
```

**Comment by jeff1evesque** [comment]
18e1326: when we submit the same form submission as [above](https://github.com/jeff1evesque/machine-learning/issues/5#issuecomment-246152410), we get the following traceback error:

```bash
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ python app.py
'Response' object has no attribute 'seek'
[AttributeError("'Response' object has no attribute 'seek'",)]
```

**Comment by jeff1evesque** [comment]
defe3c1: when we submit the same form submission as [above](https://github.com/jeff1evesque/machine-learning/issues/5#issuecomment-246152410), we get the following traceback error:

```bash
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ python app.py
[2016-09-11 13:09:02,139] ERROR in app: Exception on /load-data/ [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/interface/views.py", line 122, in load_data
    response = loader.load_data_new()
  File "/vagrant/brain/load_data.py", line 75, in load_data_new
    session.save_observation_label('data_new', session_id)
  File "/vagrant/brain/session/base_data.py", line 155, in save_observation_label
    self.premodel_data['data']['dataset']['file_upload']
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by jeff1evesque** [comment]
When we implement a `print` statement within `brain/session/base_data.py` as follows:

```python
...
    def save_observation_label(self, session_type, session_id):
        '''save_observation_label

        This method saves the list of unique independent variable labels,
        which can be expected in any given observation, into the sql
        database. This list of labels, is predicated on a supplied session
        id (entity id).

        @self.observation_labels, list of features (independent variables),
            defined after invoking the 'dataset_to_dict' method.

        @session_id, the corresponding returned session id from invoking the
            'save_entity' method.

        '''

        print self.premodel_data
        # save observation labels
        response = observation_label(
            session_type,
            session_id,
            self.observation_labels[0],
            self.premodel_data['data']['dataset']['file_upload']
        )
...
```

then, submit the same form submission as [above](https://github.com/jeff1evesque/machine-learning/issues/5#issuecomment-246152410), we get the following traceback error:

```bash
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ python app.py
{'data': {'dataset': None, 'settings': {'model_type': u'svm', 'session_name': u'test', 'dataset_type': u'dataset_url', 'dataset[]': [{'type': u'json', 'file': <cStringIO.StringI object at 0x7fbb4e319360>, 'filename': u'svm.json'}, {'type': u'json', 'file': <cStringIO.StringI object at 0x7fbb4e3192d8>, 'filename': u'svm.json'}], 'session_type': u'data_new'}}, 'error': None}
[2016-09-11 16:40:57,728] ERROR in app: Exception on /load-data/ [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/interface/views.py", line 122, in load_data
    response = loader.load_data_new()
  File "/vagrant/brain/load_data.py", line 75, in load_data_new
    session.save_observation_label('data_new', session_id)
  File "/vagrant/brain/session/base_data.py", line 156, in save_observation_label
    self.premodel_data['data']['dataset']['file_upload']
TypeError: 'NoneType' object has no attribute '__getitem__'
```
 However, if we submit a trivial svm *data new* session:

![screen shot 2016-09-11 at 4 37 55 pm](https://cloud.githubusercontent.com/assets/2907085/18420328/270b05fc-783e-11e6-9a1f-f904552ce0a1.png)

we get the following (no error) traceback statement associated with the above `print` statement:

```bash
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ python app.py
{'data': {'dataset': {'file_upload': [{'type': u'json', 'file': <FileStorage: u'svm-1.json' ('application/json')>, 'filename': u'svm-1.json'}], 'json_string': None, 'upload_quantity': 1}, 'settings': {'model_type': u'svm', 'session_name': u'test', 'dataset_type': u'file_upload', 'session_type': u'data_new'}}, 'error': None}
```

From above, we immediately notice the difference between the two session instances, namely the existence of the `'file_upload'` key during the latter session.  Specifically, the missing `file_upload` key, may contribute to the former traceback error:

```bash
...
  File "/vagrant/brain/session/base_data.py", line 156, in save_observation_label
    self.premodel_data['data']['dataset']['file_upload']
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by jeff1evesque** [comment]
The web-interface can now successfully execute the [above](https://github.com/jeff1evesque/machine-learning/issues/5#issuecomment-246152410) form submission.  Specifically, successive *model generate*, and *model predict* will succeed using the latter *data new* session.  However, since the [above](https://github.com/jeff1evesque/machine-learning/issues/5#issuecomment-246152410) form submission only include links to json dataset, we need to check both csv, and xml datasets.  Then, we need to implement the corresponding solution for the programmatic interface.

**Comment by jeff1evesque** [comment]
7d31a75: all cases, with the exception of the programmatic-interface has been successfully tested.

**Comment by jeff1evesque** [comment]
We needed to restructure our manual `pytest` directory to accommodate additional unit test cases.  Upon executing our manual unit tests, we receive the following error traceback:

```bash
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ (cd test && pytest manual)
========================================== test session starts ==========================================
platform linux2 -- Python 2.7.6, pytest-3.0.2, py-1.4.31, pluggy-0.3.1
rootdir: /vagrant/test/manual, inifile: pytest.ini
plugins: flask-0.10.0
collected 8 items / 1 errors

================================================ ERRORS =================================================
_______________ ERROR collecting programmatic_interface/file_upload/pytest_svm_session.py _______________
import file mismatch:
imported module 'pytest_svm_session' has this __file__ attribute:
  /vagrant/test/manual/programmatic_interface/dataset_url/pytest_svm_session.py
which is not the same as the test file we want to collect:
  /vagrant/test/manual/programmatic_interface/file_upload/pytest_svm_session.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
======================================== 1 error in 0.53 seconds ========================================
```

**Comment by jeff1evesque** [comment]
b3da19c, 5c1ad52: resolves the following `import file mismatch` error traceback:

```bash
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ (cd test && pytest manual)
========================================= test session starts =========================================
platform linux2 -- Python 2.7.6, pytest-3.0.2, py-1.4.31, pluggy-0.3.1
rootdir: /vagrant/test/manual, inifile: pytest.ini
plugins: flask-0.10.0
collected 4 items / 1 errors

=============================================== ERRORS ================================================
______________ ERROR collecting programmatic_interface/file_upload/pytest_svm_session.py ______________
import file mismatch:
imported module 'pytest_svm_session' has this __file__ attribute:
  /vagrant/test/manual/programmatic_interface/dataset_url/pytest_svm_session.py
which is not the same as the test file we want to collect:
  /vagrant/test/manual/programmatic_interface/file_upload/pytest_svm_session.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
======================================= 1 error in 0.30 seconds =======================================
```

**Comment by jeff1evesque** [comment]
Since our manual unit tests required us to change the `session_id`, and `model_id` values within various sample programmatic json files, we need to make adjustments to the `live_server` unit tests.  Specifically, the adjustments means that we need to perform #2711 in this issue.  The reason for this, is because both the `manual`, and `live_server` unit tests, implement the same programmatic json files.  So, placing a fixed assumption(s) on the json files for the `manual` unit tests, would mean the same assumption(s) for the `live_server` unit tests.

**Comment by jeff1evesque** [comment]
We've `truncate`d our mariadb tables, then `FLUSHALL` our redis structures, and performed our `manual` unit tests (without a `vagrant destroy`, and `vagrant build`):

```bash
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ mysql -u root -p db_machine_learning
Enter password:
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 833
Server version: 5.5.49-MariaDB-1ubuntu0.14.04.1 (Ubuntu)

Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [db_machine_learning]> show tables
    -> ;
+-------------------------------+
| Tables_in_db_machine_learning |
+-------------------------------+
| tbl_dataset_entity            |
| tbl_feature_count             |
| tbl_feature_value             |
| tbl_model_type                |
| tbl_observation_label         |
+-------------------------------+
5 rows in set (0.00 sec)

MariaDB [db_machine_learning]> truncate tbl_dataset_entity;
Query OK, 0 rows affected (0.00 sec)

MariaDB [db_machine_learning]> truncate tbl_feature_count;
Query OK, 0 rows affected (0.01 sec)

MariaDB [db_machine_learning]> truncate tbl_feature_value;
Query OK, 0 rows affected (0.00 sec)

MariaDB [db_machine_learning]> truncate tbl_observation_label;
Query OK, 0 rows affected (0.01 sec)

MariaDB [db_machine_learning]> exit;
Bye
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ redis-cli
127.0.0.1:6379> flushall
OK
127.0.0.1:6379> exit
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ (cd test && pytest manual)
========================================= test session starts =========================================
platform linux2 -- Python 2.7.6, pytest-3.0.2, py-1.4.31, pluggy-0.3.1
rootdir: /vagrant/test/manual, inifile: pytest.ini
plugins: flask-0.10.0
collected 16 items

manual/programmatic_interface/dataset_url/pytest_svm_session.py ....
manual/programmatic_interface/dataset_url/pytest_svr_session.py ..FF
manual/programmatic_interface/file_upload/pytest_svm_session.py ....
manual/programmatic_interface/file_upload/pytest_svr_session.py ....

============================================== FAILURES ===============================================
_________________________________________ test_model_generate _________________________________________

    def test_model_generate():
        '''@test_model_generate

        This method tests the 'model_generate' session.

        '''

>       assert requests.post(
            endpoint_url,
            headers=headers,
            data=get_sample_json('svr-model-generate.json', 'svr')
        )
E       assert <Response [500]>
E        +  where <Response [500]> = <function post at 0x7fdef9b6b1b8>('http://localhost:5000/load-data/', headers={'Content-Type': 'application/json'}, data='{"properties": {"model_type": "svr", "sv_kernel_type": "rbf", "session_id": "2", "session_type": "model_generate"}}')
E        +    where <function post at 0x7fdef9b6b1b8> = requests.post
E        +    and   '{"properties": {"model_type": "svr", "sv_kernel_type": "rbf", "session_id": "2", "session_type": "model_generate"}}' = get_sample_json('svr-model-generate.json', 'svr')

manual/programmatic_interface/dataset_url/pytest_svr_session.py:99: AssertionError
_________________________________________ test_model_predict __________________________________________

    def test_model_predict():
        '''@test_model_predict

        This method tests the 'model_predict' session.

        '''

>       assert requests.post(
            endpoint_url,
            headers=headers,
            data=get_sample_json('svr-model-predict.json', 'svr')
        )
E       assert <Response [500]>
E        +  where <Response [500]> = <function post at 0x7fdef9b6b1b8>('http://localhost:5000/load-data/', headers={'Content-Type': 'application/json'}, data='{"properties": {"model_id": "2", "prediction_input[]": ["22.22", "96.24", "338", "72.55", "0.001", "28", "0.678"], "session_type": "model_predict"}}')
E        +    where <function post at 0x7fdef9b6b1b8> = requests.post
E        +    and   '{"properties": {"model_id": "2", "prediction_input[]": ["22.22", "96.24", "338", "72.55", "0.001", "28", "0.678"], "session_type": "model_predict"}}' = get_sample_json('svr-model-predict.json', 'svr')

manual/programmatic_interface/dataset_url/pytest_svr_session.py:113: AssertionError
================================ 2 failed, 14 passed in 52.94 seconds =================================
```

**Comment by jeff1evesque** [comment]
We've `truncate`d our mariadb tables, then `FLUSHALL` our redis structures, and performed our `manual` unit tests (without a `vagrant destroy`, and `vagrant build`):

```bash
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ mysql -u root -p db_machine_learning
Enter password:
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 833
Server version: 5.5.49-MariaDB-1ubuntu0.14.04.1 (Ubuntu)

Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [db_machine_learning]> show tables;
+-------------------------------+
| Tables_in_db_machine_learning |
+-------------------------------+
| tbl_dataset_entity            |
| tbl_feature_count             |
| tbl_feature_value             |
| tbl_model_type                |
| tbl_observation_label         |
+-------------------------------+
5 rows in set (0.00 sec)

MariaDB [db_machine_learning]> truncate tbl_dataset_entity;
Query OK, 0 rows affected (0.00 sec)

MariaDB [db_machine_learning]> truncate tbl_feature_count;
Query OK, 0 rows affected (0.01 sec)

MariaDB [db_machine_learning]> truncate tbl_feature_value;
Query OK, 0 rows affected (0.00 sec)

MariaDB [db_machine_learning]> truncate tbl_observation_label;
Query OK, 0 rows affected (0.01 sec)

MariaDB [db_machine_learning]> exit;
Bye
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ redis-cli
127.0.0.1:6379> flushall
OK
127.0.0.1:6379> exit
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ (cd test && pytest manual)
========================================= test session starts =========================================
platform linux2 -- Python 2.7.6, pytest-3.0.2, py-1.4.31, pluggy-0.3.1
rootdir: /vagrant/test/manual, inifile: pytest.ini
plugins: flask-0.10.0
collected 16 items

manual/programmatic_interface/dataset_url/pytest_svm_session.py ....
manual/programmatic_interface/dataset_url/pytest_svr_session.py ..FF
manual/programmatic_interface/file_upload/pytest_svm_session.py ....
manual/programmatic_interface/file_upload/pytest_svr_session.py ....

============================================== FAILURES ===============================================
_________________________________________ test_model_generate _________________________________________

    def test_model_generate():
        '''@test_model_generate

        This method tests the 'model_generate' session.

        '''

>       assert requests.post(
            endpoint_url,
            headers=headers,
            data=get_sample_json('svr-model-generate.json', 'svr')
        )
E       assert <Response [500]>
E        +  where <Response [500]> = <function post at 0x7fdef9b6b1b8>('http://localhost:5000/load-data/', headers={'Content-Type': 'application/json'}, data='{"properties": {"model_type": "svr", "sv_kernel_type": "rbf", "session_id": "2", "session_type": "model_generate"}}')
E        +    where <function post at 0x7fdef9b6b1b8> = requests.post
E        +    and   '{"properties": {"model_type": "svr", "sv_kernel_type": "rbf", "session_id": "2", "session_type": "model_generate"}}' = get_sample_json('svr-model-generate.json', 'svr')

manual/programmatic_interface/dataset_url/pytest_svr_session.py:99: AssertionError
_________________________________________ test_model_predict __________________________________________

    def test_model_predict():
        '''@test_model_predict

        This method tests the 'model_predict' session.

        '''

>       assert requests.post(
            endpoint_url,
            headers=headers,
            data=get_sample_json('svr-model-predict.json', 'svr')
        )
E       assert <Response [500]>
E        +  where <Response [500]> = <function post at 0x7fdef9b6b1b8>('http://localhost:5000/load-data/', headers={'Content-Type': 'application/json'}, data='{"properties": {"model_id": "2", "prediction_input[]": ["22.22", "96.24", "338", "72.55", "0.001", "28", "0.678"], "session_type": "model_predict"}}')
E        +    where <function post at 0x7fdef9b6b1b8> = requests.post
E        +    and   '{"properties": {"model_id": "2", "prediction_input[]": ["22.22", "96.24", "338", "72.55", "0.001", "28", "0.678"], "session_type": "model_predict"}}' = get_sample_json('svr-model-predict.json', 'svr')

manual/programmatic_interface/dataset_url/pytest_svr_session.py:113: AssertionError
================================ 2 failed, 14 passed in 52.94 seconds =================================
```
