### ISSUE TITLE
Define 'Model_Generate' class in 'model_generate.py'

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/machine-learning#726]
We will define the necessary logic needed to generate an SVM model.  This logic will implement the python *scikit-learn* framework.

**Comment by jeff1evesque** [comment]
We need to group features together based on the same observation, or `id_entity`.

**Comment by jeff1evesque** [comment]
We need to query the `tbl_feature_count` database table.  Specifically, if we use `self.session_id`, we can determine the number of features that should be present for observations within the given dataset instance (`self.session_id`).

**Comment by jeff1evesque** [comment]
After #1700 has been resolved, we will implement the `get_count` method.  Specifically, this method will be used to group the returned `dataset` value into mod-x, where `x` is the value returned, or the number of features that can be expected within any given observation in a (merged) dataset.

**Comment by jeff1evesque** [comment]
We have the following traceback error:

```bash
$ python app.py
 * Running on http://127.0.0.1:5000/
 * Restarting with reloader
127.0.0.1 - - [05/Apr/2015 09:49:03] "POST /load-data/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/web_interface/views.py", line 40, in load_data
    elif session_type == 'model_generate': response = loader.load_model_generate()
  File "/var/www/brain/load_data.py", line 96, in load_model_generate
    session.generate_model()
  File "/var/www/brain/session/model_generate.py", line 79, in generate_model
    clf.fit(grouped_features, encoded_labels)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/svm/base.py", line 149, in fit
    (X.shape[0], y.shape[0]))
ValueError: X and y have incompatible shapes.
X has 13 samples, but y has 5.
```

**Comment by jeff1evesque** [comment]
We need to fix the docblock for `generate_model`.
